// Code generated from backend/openapi/api.yaml contract surface. DO NOT EDIT.
// backend/openapi/contract_test.go verifies this file stays synchronized.

export const API_OPERATIONS = [
  { method: "POST", path: "/api/v1/admin/attempts/{attemptID}/usage", operationId: "postApiV1AdminAttemptsAttemptidUsage" },
  { method: "POST", path: "/api/v1/admin/attention/{itemID}/resolve", operationId: "postApiV1AdminAttentionItemidResolve" },
  { method: "GET", path: "/api/v1/admin/audit", operationId: "getApiV1AdminAudit" },
  { method: "GET", path: "/api/v1/admin/audit/{eventID}", operationId: "getApiV1AdminAuditEventid" },
  { method: "POST", path: "/api/v1/admin/canon-branches/{branchID}/commit", operationId: "postApiV1AdminCanonBranchesBranchidCommit" },
  { method: "POST", path: "/api/v1/admin/canon-branches/{branchID}/provisional-versions", operationId: "postApiV1AdminCanonBranchesBranchidProvisionalVersions" },
  { method: "GET", path: "/api/v1/admin/canon-branches/{branchID}/versions", operationId: "getApiV1AdminCanonBranchesBranchidVersions" },
  { method: "POST", path: "/api/v1/admin/canon-branches/{branchID}/versions", operationId: "postApiV1AdminCanonBranchesBranchidVersions" },
  { method: "POST", path: "/api/v1/admin/canon-versions/{versionID}/promote", operationId: "postApiV1AdminCanonVersionsVersionidPromote" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/approve", operationId: "postApiV1AdminChaptersChapteridApprove" },
  { method: "GET", path: "/api/v1/admin/chapters/{chapterID}/audio", operationId: "getApiV1AdminChaptersChapteridAudio" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/audio", operationId: "postApiV1AdminChaptersChapteridAudio" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/audio/{assetID}/activate", operationId: "postApiV1AdminChaptersChapteridAudioAssetidActivate" },
  { method: "GET", path: "/api/v1/admin/chapters/{chapterID}/content", operationId: "getApiV1AdminChaptersChapteridContent" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/content", operationId: "postApiV1AdminChaptersChapteridContent" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/continuity", operationId: "postApiV1AdminChaptersChapteridContinuity" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/duration", operationId: "postApiV1AdminChaptersChapteridDuration" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/edit", operationId: "postApiV1AdminChaptersChapteridEdit" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/narration", operationId: "postApiV1AdminChaptersChapteridNarration" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/narration/{narrationID}/segments", operationId: "postApiV1AdminChaptersChapteridNarrationNarrationidSegments" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/narration/{narrationID}/synthesize", operationId: "postApiV1AdminChaptersChapteridNarrationNarrationidSynthesize" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/plans", operationId: "postApiV1AdminChaptersChapteridPlans" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/publish", operationId: "postApiV1AdminChaptersChapteridPublish" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/quality", operationId: "postApiV1AdminChaptersChapteridQuality" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/regenerate", operationId: "postApiV1AdminChaptersChapteridRegenerate" },
  { method: "GET", path: "/api/v1/admin/chapters/{chapterID}/reviews", operationId: "getApiV1AdminChaptersChapteridReviews" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/reviews", operationId: "postApiV1AdminChaptersChapteridReviews" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/revision-impact", operationId: "postApiV1AdminChaptersChapteridRevisionImpact" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/rewrite", operationId: "postApiV1AdminChaptersChapteridRewrite" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/safety", operationId: "postApiV1AdminChaptersChapteridSafety" },
  { method: "POST", path: "/api/v1/admin/chapters/{chapterID}/unpublish", operationId: "postApiV1AdminChaptersChapteridUnpublish" },
  { method: "GET", path: "/api/v1/admin/context-snapshots/{snapshotID}", operationId: "getApiV1AdminContextSnapshotsSnapshotid" },
  { method: "POST", path: "/api/v1/admin/creative-decisions/{decisionID}/reject", operationId: "postApiV1AdminCreativeDecisionsDecisionidReject" },
  { method: "POST", path: "/api/v1/admin/creative-decisions/{decisionID}/select", operationId: "postApiV1AdminCreativeDecisionsDecisionidSelect" },
  { method: "POST", path: "/api/v1/admin/plot-threads/{threadID}/events", operationId: "postApiV1AdminPlotThreadsThreadidEvents" },
  { method: "GET", path: "/api/v1/admin/retcons", operationId: "getApiV1AdminRetcons" },
  { method: "POST", path: "/api/v1/admin/retcons", operationId: "postApiV1AdminRetcons" },
  { method: "GET", path: "/api/v1/admin/retcons/{id}", operationId: "getApiV1AdminRetconsId" },
  { method: "POST", path: "/api/v1/admin/retcons/{id}/analyze", operationId: "postApiV1AdminRetconsIdAnalyze" },
  { method: "POST", path: "/api/v1/admin/retcons/{id}/apply", operationId: "postApiV1AdminRetconsIdApply" },
  { method: "POST", path: "/api/v1/admin/retcons/{id}/approve", operationId: "postApiV1AdminRetconsIdApprove" },
  { method: "POST", path: "/api/v1/admin/retcons/{id}/cancel", operationId: "postApiV1AdminRetconsIdCancel" },
  { method: "POST", path: "/api/v1/admin/retcons/{id}/ready", operationId: "postApiV1AdminRetconsIdReady" },
  { method: "POST", path: "/api/v1/admin/revisions/{revisionID}/reject", operationId: "postApiV1AdminRevisionsRevisionidReject" },
  { method: "POST", path: "/api/v1/admin/runs", operationId: "postApiV1AdminRuns" },
  { method: "GET", path: "/api/v1/admin/runs/{runID}", operationId: "getApiV1AdminRunsRunid" },
  { method: "POST", path: "/api/v1/admin/runs/{runID}/jobs", operationId: "postApiV1AdminRunsRunidJobs" },
  { method: "POST", path: "/api/v1/admin/runs/{runID}/mark-stale", operationId: "postApiV1AdminRunsRunidMarkStale" },
  { method: "GET", path: "/api/v1/admin/stories", operationId: "getApiV1AdminStories" },
  { method: "POST", path: "/api/v1/admin/stories", operationId: "postApiV1AdminStories" },
  { method: "POST", path: "/api/v1/admin/stories/{storyID}/activate", operationId: "postApiV1AdminStoriesStoryidActivate" },
  { method: "POST", path: "/api/v1/admin/stories/{storyID}/archive", operationId: "postApiV1AdminStoriesStoryidArchive" },
  { method: "GET", path: "/api/v1/admin/stories/{storyID}/arcs", operationId: "getApiV1AdminStoriesStoryidArcs" },
  { method: "GET", path: "/api/v1/admin/stories/{storyID}/arcs/{arcID}/completion", operationId: "getApiV1AdminStoriesStoryidArcsArcidCompletion" },
  { method: "GET", path: "/api/v1/admin/stories/{storyID}/attention", operationId: "getApiV1AdminStoriesStoryidAttention" },
  { method: "POST", path: "/api/v1/admin/stories/{storyID}/attention", operationId: "postApiV1AdminStoriesStoryidAttention" },
  { method: "POST", path: "/api/v1/admin/stories/{storyID}/batch-generate", operationId: "postApiV1AdminStoriesStoryidBatchGenerate" },
  { method: "GET", path: "/api/v1/admin/stories/{storyID}/bible", operationId: "getApiV1AdminStoriesStoryidBible" },
  { method: "POST", path: "/api/v1/admin/stories/{storyID}/canon-branches", operationId: "postApiV1AdminStoriesStoryidCanonBranches" },
  { method: "POST", path: "/api/v1/admin/stories/{storyID}/canon-repair", operationId: "postApiV1AdminStoriesStoryidCanonRepair" },
  { method: "GET", path: "/api/v1/admin/stories/{storyID}/chapters", operationId: "getApiV1AdminStoriesStoryidChapters" },
  { method: "POST", path: "/api/v1/admin/stories/{storyID}/chapters", operationId: "postApiV1AdminStoriesStoryidChapters" },
  { method: "GET", path: "/api/v1/admin/stories/{storyID}/characters", operationId: "getApiV1AdminStoriesStoryidCharacters" },
  { method: "GET", path: "/api/v1/admin/stories/{storyID}/content-profile", operationId: "getApiV1AdminStoriesStoryidContentProfile" },
  { method: "POST", path: "/api/v1/admin/stories/{storyID}/content-profile", operationId: "postApiV1AdminStoriesStoryidContentProfile" },
  { method: "GET", path: "/api/v1/admin/stories/{storyID}/context-snapshots", operationId: "getApiV1AdminStoriesStoryidContextSnapshots" },
  { method: "POST", path: "/api/v1/admin/stories/{storyID}/context-snapshots", operationId: "postApiV1AdminStoriesStoryidContextSnapshots" },
  { method: "POST", path: "/api/v1/admin/stories/{storyID}/cover", operationId: "postApiV1AdminStoriesStoryidCover" },
  { method: "GET", path: "/api/v1/admin/stories/{storyID}/creative-decisions", operationId: "getApiV1AdminStoriesStoryidCreativeDecisions" },
  { method: "POST", path: "/api/v1/admin/stories/{storyID}/creative-decisions", operationId: "postApiV1AdminStoriesStoryidCreativeDecisions" },
  { method: "GET", path: "/api/v1/admin/stories/{storyID}/ending", operationId: "getApiV1AdminStoriesStoryidEnding" },
  { method: "GET", path: "/api/v1/admin/stories/{storyID}/facts", operationId: "getApiV1AdminStoriesStoryidFacts" },
  { method: "POST", path: "/api/v1/admin/stories/{storyID}/facts", operationId: "postApiV1AdminStoriesStoryidFacts" },
  { method: "POST", path: "/api/v1/admin/stories/{storyID}/foundation", operationId: "postApiV1AdminStoriesStoryidFoundation" },
  { method: "POST", path: "/api/v1/admin/stories/{storyID}/make-private", operationId: "postApiV1AdminStoriesStoryidMakePrivate" },
  { method: "POST", path: "/api/v1/admin/stories/{storyID}/make-public", operationId: "postApiV1AdminStoriesStoryidMakePublic" },
  { method: "GET", path: "/api/v1/admin/stories/{storyID}/plot-threads", operationId: "getApiV1AdminStoriesStoryidPlotThreads" },
  { method: "POST", path: "/api/v1/admin/stories/{storyID}/plot-threads", operationId: "postApiV1AdminStoriesStoryidPlotThreads" },
  { method: "POST", path: "/api/v1/admin/stories/{storyID}/restore", operationId: "postApiV1AdminStoriesStoryidRestore" },
  { method: "GET", path: "/api/v1/admin/stories/{storyID}/thread-inactivity", operationId: "getApiV1AdminStoriesStoryidThreadInactivity" },
  { method: "GET", path: "/api/v1/admin/stories/{storyID}/usage", operationId: "getApiV1AdminStoriesStoryidUsage" },
  { method: "GET", path: "/api/v1/admin/stories/{storyID}/workflow-settings", operationId: "getApiV1AdminStoriesStoryidWorkflowSettings" },
  { method: "PUT", path: "/api/v1/admin/stories/{storyID}/workflow-settings", operationId: "putApiV1AdminStoriesStoryidWorkflowSettings" },
  { method: "POST", path: "/api/v1/admin/tts-segments/{segmentID}/synthesize", operationId: "postApiV1AdminTtsSegmentsSegmentidSynthesize" },
  { method: "POST", path: "/api/v1/auth/account/deletion/cancel", operationId: "postApiV1AuthAccountDeletionCancel" },
  { method: "POST", path: "/api/v1/auth/account/deletion/request", operationId: "postApiV1AuthAccountDeletionRequest" },
  { method: "POST", path: "/api/v1/auth/email/resend", operationId: "postApiV1AuthEmailResend" },
  { method: "POST", path: "/api/v1/auth/email/verify", operationId: "postApiV1AuthEmailVerify" },
  { method: "POST", path: "/api/v1/auth/login", operationId: "postApiV1AuthLogin" },
  { method: "POST", path: "/api/v1/auth/logout", operationId: "postApiV1AuthLogout" },
  { method: "POST", path: "/api/v1/auth/logout-all", operationId: "postApiV1AuthLogoutAll" },
  { method: "GET", path: "/api/v1/auth/me", operationId: "getApiV1AuthMe" },
  { method: "POST", path: "/api/v1/auth/mfa/totp/confirm", operationId: "postApiV1AuthMfaTotpConfirm" },
  { method: "POST", path: "/api/v1/auth/mfa/totp/disable", operationId: "postApiV1AuthMfaTotpDisable" },
  { method: "POST", path: "/api/v1/auth/mfa/totp/setup", operationId: "postApiV1AuthMfaTotpSetup" },
  { method: "POST", path: "/api/v1/auth/password/forgot", operationId: "postApiV1AuthPasswordForgot" },
  { method: "POST", path: "/api/v1/auth/password/reset", operationId: "postApiV1AuthPasswordReset" },
  { method: "POST", path: "/api/v1/auth/refresh", operationId: "postApiV1AuthRefresh" },
  { method: "POST", path: "/api/v1/auth/register", operationId: "postApiV1AuthRegister" },
  { method: "GET", path: "/api/v1/auth/sessions", operationId: "getApiV1AuthSessions" },
  { method: "DELETE", path: "/api/v1/auth/sessions/{sessionID}", operationId: "deleteApiV1AuthSessionsSessionid" },
  { method: "GET", path: "/api/v1/chapters/{chapterID}/audio-url", operationId: "getApiV1ChaptersChapteridAudioUrl" },
  { method: "GET", path: "/api/v1/chapters/{chapterID}/content", operationId: "getApiV1ChaptersChapteridContent" },
  { method: "GET", path: "/api/v1/genres", operationId: "getApiV1Genres" },
  { method: "GET", path: "/api/v1/me/favorites", operationId: "getApiV1MeFavorites" },
  { method: "DELETE", path: "/api/v1/me/favorites/{storyID}", operationId: "deleteApiV1MeFavoritesStoryid" },
  { method: "PUT", path: "/api/v1/me/favorites/{storyID}", operationId: "putApiV1MeFavoritesStoryid" },
  { method: "GET", path: "/api/v1/me/progress/{chapterID}", operationId: "getApiV1MeProgressChapterid" },
  { method: "PUT", path: "/api/v1/me/progress/{chapterID}", operationId: "putApiV1MeProgressChapterid" },
  { method: "POST", path: "/api/v1/me/progress/{chapterID}/complete", operationId: "postApiV1MeProgressChapteridComplete" },
  { method: "GET", path: "/api/v1/stories", operationId: "getApiV1Stories" },
  { method: "GET", path: "/api/v1/stories/{storyID}", operationId: "getApiV1StoriesStoryid" },
  { method: "GET", path: "/api/v1/stories/{storyID}/chapters", operationId: "getApiV1StoriesStoryidChapters" },
  { method: "GET", path: "/health", operationId: "getHealth" },
  { method: "GET", path: "/ready", operationId: "getReady" },
] as const

export type ApiOperation = (typeof API_OPERATIONS)[number]
export type ApiMethod = ApiOperation["method"]
export type ApiPath = ApiOperation["path"]
export type ApiOperationId = ApiOperation["operationId"]

export interface ApiErrorResponse {
  status?: string
  error: string
  code?: string
  message?: string
}
