DELETE FROM role_permissions rp
USING roles r, permissions p
WHERE rp.role_id = r.id
  AND rp.permission_id = p.id
  AND r.code = 'ADMIN'
  AND p.code IN (
    'STORY_CREATE','STORY_METADATA_EDIT','STORY_ACTIVATE','STORY_ARCHIVE','STORY_RESTORE','STORY_VISIBILITY_MANAGE','STORY_WORKFLOW_SETTINGS_MANAGE',
    'STORY_BIBLE_VIEW','STORY_BIBLE_MANAGE','CHARACTER_VIEW','CHARACTER_MANAGE','ARC_VIEW','ARC_MANAGE','ENDING_PLAN_VIEW','ENDING_PLAN_MANAGE','CHAPTER_PLAN_VIEW','CHAPTER_PLAN_MANAGE','STORY_FACT_VIEW','PLOT_THREAD_VIEW',
    'CHAPTER_CREATE','CHAPTER_GENERATE','CHAPTER_EDIT_DRAFT','CHAPTER_REVIEW','CHAPTER_APPROVE_CONTENT','CHAPTER_REVISE_PRE_PUBLISH','CHAPTER_PUBLISH','CHAPTER_UNPUBLISH','CHAPTER_ARCHIVE',
    'GENERATION_VIEW','GENERATION_START','GENERATION_RETRY','GENERATION_REGENERATE','GENERATION_REWRITE','GENERATION_CANCEL',
    'CANON_VIEW','CANON_HISTORY_VIEW','STORY_MEMORY_VIEW','CANON_DATA_REPAIR_REQUEST','CANON_DATA_REPAIR_APPLY',
    'CREATIVE_DECISION_VIEW','CREATIVE_DECISION_RESOLVE','CREATIVE_DECISION_POSTPONE','CREATIVE_DECISION_REJECT',
    'RETCON_VIEW','RETCON_REQUEST','RETCON_APPROVE','RETCON_APPLY','RETCON_CANCEL',
    'NARRATION_VIEW','NARRATION_GENERATE','NARRATION_EDIT','NARRATION_APPROVE','AUDIO_GENERATE','AUDIO_RETRY','AUDIO_REVIEW','AUDIO_ACTIVATE_VERSION',
    'AUDIT_VIEW','USER_STATUS_MANAGE','ADMIN_ROLE_GRANT','ADMIN_ROLE_REVOKE','ADMIN_STATUS_MANAGE','SECURITY_EVENT_VIEW'
  );

DELETE FROM permissions
WHERE code IN (
    'STORY_CREATE','STORY_METADATA_EDIT','STORY_ACTIVATE','STORY_ARCHIVE','STORY_RESTORE','STORY_VISIBILITY_MANAGE','STORY_WORKFLOW_SETTINGS_MANAGE',
    'STORY_BIBLE_VIEW','STORY_BIBLE_MANAGE','CHARACTER_VIEW','CHARACTER_MANAGE','ARC_VIEW','ARC_MANAGE','ENDING_PLAN_VIEW','ENDING_PLAN_MANAGE','CHAPTER_PLAN_VIEW','CHAPTER_PLAN_MANAGE','STORY_FACT_VIEW','PLOT_THREAD_VIEW',
    'CHAPTER_CREATE','CHAPTER_GENERATE','CHAPTER_EDIT_DRAFT','CHAPTER_REVIEW','CHAPTER_APPROVE_CONTENT','CHAPTER_REVISE_PRE_PUBLISH','CHAPTER_PUBLISH','CHAPTER_UNPUBLISH','CHAPTER_ARCHIVE',
    'GENERATION_VIEW','GENERATION_START','GENERATION_RETRY','GENERATION_REGENERATE','GENERATION_REWRITE','GENERATION_CANCEL',
    'CANON_VIEW','CANON_HISTORY_VIEW','STORY_MEMORY_VIEW','CANON_DATA_REPAIR_REQUEST','CANON_DATA_REPAIR_APPLY',
    'CREATIVE_DECISION_VIEW','CREATIVE_DECISION_RESOLVE','CREATIVE_DECISION_POSTPONE','CREATIVE_DECISION_REJECT',
    'RETCON_VIEW','RETCON_REQUEST','RETCON_APPROVE','RETCON_APPLY','RETCON_CANCEL',
    'NARRATION_VIEW','NARRATION_GENERATE','NARRATION_EDIT','NARRATION_APPROVE','AUDIO_GENERATE','AUDIO_RETRY','AUDIO_REVIEW','AUDIO_ACTIVATE_VERSION',
    'AUDIT_VIEW','USER_STATUS_MANAGE','ADMIN_ROLE_GRANT','ADMIN_ROLE_REVOKE','ADMIN_STATUS_MANAGE','SECURITY_EVENT_VIEW'
  );
