// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (
    id, actor_user_id, actor_type, action, resource_type, resource_id,
    story_id, chapter_id, result, correlation_id, request_id,
    generation_run_id, provenance, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, actor_user_id, actor_type, action, resource_type, resource_id,
          story_id, chapter_id, result, correlation_id, request_id,
          generation_run_id, provenance, metadata, created_at
`

type CreateAuditEventParams struct {
	ID              pgtype.UUID `json:"id"`
	ActorUserID     pgtype.UUID `json:"actor_user_id"`
	ActorType       string      `json:"actor_type"`
	Action          string      `json:"action"`
	ResourceType    pgtype.Text `json:"resource_type"`
	ResourceID      pgtype.Text `json:"resource_id"`
	StoryID         pgtype.UUID `json:"story_id"`
	ChapterID       pgtype.UUID `json:"chapter_id"`
	Result          string      `json:"result"`
	CorrelationID   pgtype.Text `json:"correlation_id"`
	RequestID       pgtype.Text `json:"request_id"`
	GenerationRunID pgtype.UUID `json:"generation_run_id"`
	Provenance      []byte      `json:"provenance"`
	Metadata        []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.ID,
		arg.ActorUserID,
		arg.ActorType,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.StoryID,
		arg.ChapterID,
		arg.Result,
		arg.CorrelationID,
		arg.RequestID,
		arg.GenerationRunID,
		arg.Provenance,
		arg.Metadata,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.ActorType,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.StoryID,
		&i.ChapterID,
		&i.Result,
		&i.CorrelationID,
		&i.RequestID,
		&i.GenerationRunID,
		&i.Provenance,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditEvent = `-- name: GetAuditEvent :one
SELECT id, actor_user_id, actor_type, action, resource_type, resource_id,
       story_id, chapter_id, result, correlation_id, request_id,
       generation_run_id, provenance, metadata, created_at
FROM audit_events
WHERE id = $1
`

func (q *Queries) GetAuditEvent(ctx context.Context, id pgtype.UUID) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, getAuditEvent, id)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.ActorType,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.StoryID,
		&i.ChapterID,
		&i.Result,
		&i.CorrelationID,
		&i.RequestID,
		&i.GenerationRunID,
		&i.Provenance,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, actor_user_id, actor_type, action, resource_type, resource_id,
       story_id, chapter_id, result, correlation_id, request_id,
       generation_run_id, provenance, metadata, created_at
FROM audit_events
WHERE ($1::uuid IS NULL OR actor_user_id = $1)
  AND ($2::text IS NULL OR action = $2)
  AND ($3::text IS NULL OR resource_type = $3)
  AND ($4::text IS NULL OR resource_id = $4)
  AND ($5::uuid IS NULL OR story_id = $5)
  AND ($6::uuid IS NULL OR chapter_id = $6)
  AND ($7::uuid IS NULL OR generation_run_id = $7)
  AND ($8::text IS NULL OR correlation_id = $8)
  AND ($9::text IS NULL OR result = $9)
  AND ($10::timestamptz IS NULL OR created_at >= $10)
  AND ($11::timestamptz IS NULL OR created_at <= $11)
ORDER BY created_at DESC, id DESC
LIMIT $12
`

type ListAuditEventsParams struct {
	Column1  pgtype.UUID        `json:"column_1"`
	Column2  string             `json:"column_2"`
	Column3  string             `json:"column_3"`
	Column4  string             `json:"column_4"`
	Column5  pgtype.UUID        `json:"column_5"`
	Column6  pgtype.UUID        `json:"column_6"`
	Column7  pgtype.UUID        `json:"column_7"`
	Column8  string             `json:"column_8"`
	Column9  string             `json:"column_9"`
	Column10 pgtype.Timestamptz `json:"column_10"`
	Column11 pgtype.Timestamptz `json:"column_11"`
	Limit    int32              `json:"limit"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorType,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.StoryID,
			&i.ChapterID,
			&i.Result,
			&i.CorrelationID,
			&i.RequestID,
			&i.GenerationRunID,
			&i.Provenance,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
