// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audio.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAudioAsset = `-- name: CreateAudioAsset :one
INSERT INTO audio_assets (id, chapter_id, version_no, source_narration_revision_id,
                          status, storage_key, mime_type, size_bytes, duration_ms,
                          bitrate_kbps, checksum, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, chapter_id, version_no, source_narration_revision_id, status, storage_key,
          mime_type, size_bytes, duration_ms, bitrate_kbps, checksum, is_active,
          generation_run_id, created_at
`

type CreateAudioAssetParams struct {
	ID                        pgtype.UUID `json:"id"`
	ChapterID                 pgtype.UUID `json:"chapter_id"`
	VersionNo                 int32       `json:"version_no"`
	SourceNarrationRevisionID pgtype.UUID `json:"source_narration_revision_id"`
	Status                    string      `json:"status"`
	StorageKey                pgtype.Text `json:"storage_key"`
	MimeType                  pgtype.Text `json:"mime_type"`
	SizeBytes                 pgtype.Int8 `json:"size_bytes"`
	DurationMs                pgtype.Int4 `json:"duration_ms"`
	BitrateKbps               pgtype.Int4 `json:"bitrate_kbps"`
	Checksum                  pgtype.Text `json:"checksum"`
	IsActive                  bool        `json:"is_active"`
}

func (q *Queries) CreateAudioAsset(ctx context.Context, arg CreateAudioAssetParams) (AudioAsset, error) {
	row := q.db.QueryRow(ctx, createAudioAsset,
		arg.ID,
		arg.ChapterID,
		arg.VersionNo,
		arg.SourceNarrationRevisionID,
		arg.Status,
		arg.StorageKey,
		arg.MimeType,
		arg.SizeBytes,
		arg.DurationMs,
		arg.BitrateKbps,
		arg.Checksum,
		arg.IsActive,
	)
	var i AudioAsset
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.VersionNo,
		&i.SourceNarrationRevisionID,
		&i.Status,
		&i.StorageKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.DurationMs,
		&i.BitrateKbps,
		&i.Checksum,
		&i.IsActive,
		&i.GenerationRunID,
		&i.CreatedAt,
	)
	return i, err
}

const createNarrationRevision = `-- name: CreateNarrationRevision :one
INSERT INTO narration_revisions (id, chapter_id, revision_no, source_content_revision_id,
                                 voice_id, script, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, chapter_id, revision_no, source_content_revision_id, voice_id, script,
          status, generation_run_id, created_by, created_at
`

type CreateNarrationRevisionParams struct {
	ID                      pgtype.UUID `json:"id"`
	ChapterID               pgtype.UUID `json:"chapter_id"`
	RevisionNo              int32       `json:"revision_no"`
	SourceContentRevisionID pgtype.UUID `json:"source_content_revision_id"`
	VoiceID                 pgtype.Text `json:"voice_id"`
	Script                  pgtype.Text `json:"script"`
	Status                  string      `json:"status"`
	CreatedBy               pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateNarrationRevision(ctx context.Context, arg CreateNarrationRevisionParams) (NarrationRevision, error) {
	row := q.db.QueryRow(ctx, createNarrationRevision,
		arg.ID,
		arg.ChapterID,
		arg.RevisionNo,
		arg.SourceContentRevisionID,
		arg.VoiceID,
		arg.Script,
		arg.Status,
		arg.CreatedBy,
	)
	var i NarrationRevision
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.RevisionNo,
		&i.SourceContentRevisionID,
		&i.VoiceID,
		&i.Script,
		&i.Status,
		&i.GenerationRunID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createTTSSegment = `-- name: CreateTTSSegment :one

INSERT INTO tts_segments (id, narration_revision_id, segment_no, text, direction,
                          status, provider, model, voice_id, duration_ms, temp_storage_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, narration_revision_id, segment_no, text, direction, status, provider,
          model, voice_id, duration_ms, temp_storage_key, generation_job_id, created_at
`

type CreateTTSSegmentParams struct {
	ID                  pgtype.UUID `json:"id"`
	NarrationRevisionID pgtype.UUID `json:"narration_revision_id"`
	SegmentNo           int32       `json:"segment_no"`
	Text                string      `json:"text"`
	Direction           []byte      `json:"direction"`
	Status              string      `json:"status"`
	Provider            pgtype.Text `json:"provider"`
	Model               pgtype.Text `json:"model"`
	VoiceID             pgtype.Text `json:"voice_id"`
	DurationMs          pgtype.Int4 `json:"duration_ms"`
	TempStorageKey      pgtype.Text `json:"temp_storage_key"`
}

// ============================================================
// TTS Segments
// ============================================================
func (q *Queries) CreateTTSSegment(ctx context.Context, arg CreateTTSSegmentParams) (TtsSegment, error) {
	row := q.db.QueryRow(ctx, createTTSSegment,
		arg.ID,
		arg.NarrationRevisionID,
		arg.SegmentNo,
		arg.Text,
		arg.Direction,
		arg.Status,
		arg.Provider,
		arg.Model,
		arg.VoiceID,
		arg.DurationMs,
		arg.TempStorageKey,
	)
	var i TtsSegment
	err := row.Scan(
		&i.ID,
		&i.NarrationRevisionID,
		&i.SegmentNo,
		&i.Text,
		&i.Direction,
		&i.Status,
		&i.Provider,
		&i.Model,
		&i.VoiceID,
		&i.DurationMs,
		&i.TempStorageKey,
		&i.GenerationJobID,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveAudioAsset = `-- name: GetActiveAudioAsset :one
SELECT id, chapter_id, version_no, source_narration_revision_id, status, storage_key,
       mime_type, size_bytes, duration_ms, bitrate_kbps, checksum, is_active,
       generation_run_id, created_at
FROM audio_assets
WHERE chapter_id = $1 AND is_active = true
`

func (q *Queries) GetActiveAudioAsset(ctx context.Context, chapterID pgtype.UUID) (AudioAsset, error) {
	row := q.db.QueryRow(ctx, getActiveAudioAsset, chapterID)
	var i AudioAsset
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.VersionNo,
		&i.SourceNarrationRevisionID,
		&i.Status,
		&i.StorageKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.DurationMs,
		&i.BitrateKbps,
		&i.Checksum,
		&i.IsActive,
		&i.GenerationRunID,
		&i.CreatedAt,
	)
	return i, err
}

const getAudioAsset = `-- name: GetAudioAsset :one
SELECT id, chapter_id, version_no, source_narration_revision_id, status, storage_key,
       mime_type, size_bytes, duration_ms, bitrate_kbps, checksum, is_active,
       generation_run_id, created_at
FROM audio_assets
WHERE id = $1
`

func (q *Queries) GetAudioAsset(ctx context.Context, id pgtype.UUID) (AudioAsset, error) {
	row := q.db.QueryRow(ctx, getAudioAsset, id)
	var i AudioAsset
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.VersionNo,
		&i.SourceNarrationRevisionID,
		&i.Status,
		&i.StorageKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.DurationMs,
		&i.BitrateKbps,
		&i.Checksum,
		&i.IsActive,
		&i.GenerationRunID,
		&i.CreatedAt,
	)
	return i, err
}

const getNarrationRevision = `-- name: GetNarrationRevision :one
SELECT id, chapter_id, revision_no, source_content_revision_id, voice_id, script,
       status, generation_run_id, created_by, created_at
FROM narration_revisions
WHERE id = $1
`

func (q *Queries) GetNarrationRevision(ctx context.Context, id pgtype.UUID) (NarrationRevision, error) {
	row := q.db.QueryRow(ctx, getNarrationRevision, id)
	var i NarrationRevision
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.RevisionNo,
		&i.SourceContentRevisionID,
		&i.VoiceID,
		&i.Script,
		&i.Status,
		&i.GenerationRunID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTTSSegment = `-- name: GetTTSSegment :one
SELECT id, narration_revision_id, segment_no, text, direction, status, provider,
       model, voice_id, duration_ms, temp_storage_key, generation_job_id, created_at
FROM tts_segments
WHERE id = $1
`

func (q *Queries) GetTTSSegment(ctx context.Context, id pgtype.UUID) (TtsSegment, error) {
	row := q.db.QueryRow(ctx, getTTSSegment, id)
	var i TtsSegment
	err := row.Scan(
		&i.ID,
		&i.NarrationRevisionID,
		&i.SegmentNo,
		&i.Text,
		&i.Direction,
		&i.Status,
		&i.Provider,
		&i.Model,
		&i.VoiceID,
		&i.DurationMs,
		&i.TempStorageKey,
		&i.GenerationJobID,
		&i.CreatedAt,
	)
	return i, err
}

const nextAudioVersion = `-- name: NextAudioVersion :one

SELECT COALESCE(MAX(version_no), 0) + 1
FROM audio_assets
WHERE chapter_id = $1
`

// ============================================================
// Audio Assets
// ============================================================
func (q *Queries) NextAudioVersion(ctx context.Context, chapterID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextAudioVersion, chapterID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextNarrationRevision = `-- name: NextNarrationRevision :one

SELECT COALESCE(MAX(revision_no), 0) + 1
FROM narration_revisions
WHERE chapter_id = $1
`

// ============================================================
// Narration Revisions
// ============================================================
func (q *Queries) NextNarrationRevision(ctx context.Context, chapterID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextNarrationRevision, chapterID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setActiveAudioAsset = `-- name: SetActiveAudioAsset :many
WITH eligible_target AS (
    SELECT id
    FROM audio_assets
    WHERE chapter_id = $1
      AND id = $2
      AND status = 'READY'
    FOR UPDATE
)
UPDATE audio_assets
SET is_active = (id = $2)
WHERE chapter_id = $1
  AND EXISTS (SELECT 1 FROM eligible_target)
RETURNING id, chapter_id, version_no, source_narration_revision_id, status, storage_key,
          mime_type, size_bytes, duration_ms, bitrate_kbps, checksum, is_active,
          generation_run_id, created_at
`

type SetActiveAudioAssetParams struct {
	ChapterID pgtype.UUID `json:"chapter_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) SetActiveAudioAsset(ctx context.Context, arg SetActiveAudioAssetParams) ([]AudioAsset, error) {
	rows, err := q.db.Query(ctx, setActiveAudioAsset, arg.ChapterID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AudioAsset{}
	for rows.Next() {
		var i AudioAsset
		if err := rows.Scan(
			&i.ID,
			&i.ChapterID,
			&i.VersionNo,
			&i.SourceNarrationRevisionID,
			&i.Status,
			&i.StorageKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.Checksum,
			&i.IsActive,
			&i.GenerationRunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTTSSegment = `-- name: UpdateTTSSegment :one
UPDATE tts_segments
SET status = $2,
    provider = $3,
    model = $4,
    duration_ms = $5,
    temp_storage_key = $6
WHERE id = $1
RETURNING id, narration_revision_id, segment_no, text, direction, status, provider,
          model, voice_id, duration_ms, temp_storage_key, generation_job_id, created_at
`

type UpdateTTSSegmentParams struct {
	ID             pgtype.UUID `json:"id"`
	Status         string      `json:"status"`
	Provider       pgtype.Text `json:"provider"`
	Model          pgtype.Text `json:"model"`
	DurationMs     pgtype.Int4 `json:"duration_ms"`
	TempStorageKey pgtype.Text `json:"temp_storage_key"`
}

func (q *Queries) UpdateTTSSegment(ctx context.Context, arg UpdateTTSSegmentParams) (TtsSegment, error) {
	row := q.db.QueryRow(ctx, updateTTSSegment,
		arg.ID,
		arg.Status,
		arg.Provider,
		arg.Model,
		arg.DurationMs,
		arg.TempStorageKey,
	)
	var i TtsSegment
	err := row.Scan(
		&i.ID,
		&i.NarrationRevisionID,
		&i.SegmentNo,
		&i.Text,
		&i.Direction,
		&i.Status,
		&i.Provider,
		&i.Model,
		&i.VoiceID,
		&i.DurationMs,
		&i.TempStorageKey,
		&i.GenerationJobID,
		&i.CreatedAt,
	)
	return i, err
}
