// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit_outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAuditIntents = `-- name: ClaimAuditIntents :many
WITH candidates AS (
    SELECT id
    FROM audit_delivery_outbox
    WHERE (
        status = 'PENDING' AND available_at <= NOW()
    ) OR (
        status = 'DELIVERING' AND locked_at <= NOW() - INTERVAL '5 minutes'
    )
    ORDER BY available_at ASC, created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
UPDATE audit_delivery_outbox o
SET status = 'DELIVERING',
    attempt_count = o.attempt_count + 1,
    locked_at = NOW(),
    updated_at = NOW()
FROM candidates c
WHERE o.id = c.id
RETURNING o.id, o.event, o.status, o.attempt_count, o.max_attempts,
          o.available_at, o.locked_at, o.last_error, o.created_at, o.updated_at
`

func (q *Queries) ClaimAuditIntents(ctx context.Context, limit int32) ([]AuditDeliveryOutbox, error) {
	rows, err := q.db.Query(ctx, claimAuditIntents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditDeliveryOutbox{}
	for rows.Next() {
		var i AuditDeliveryOutbox
		if err := rows.Scan(
			&i.ID,
			&i.Event,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.AvailableAt,
			&i.LockedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueAuditIntent = `-- name: EnqueueAuditIntent :exec
INSERT INTO audit_delivery_outbox (id, event)
VALUES ($1, $2)
ON CONFLICT (id) DO NOTHING
`

type EnqueueAuditIntentParams struct {
	ID    pgtype.UUID `json:"id"`
	Event []byte      `json:"event"`
}

func (q *Queries) EnqueueAuditIntent(ctx context.Context, arg EnqueueAuditIntentParams) error {
	_, err := q.db.Exec(ctx, enqueueAuditIntent, arg.ID, arg.Event)
	return err
}

const markAuditIntentDelivered = `-- name: MarkAuditIntentDelivered :exec
UPDATE audit_delivery_outbox
SET status = 'DELIVERED', locked_at = NULL, last_error = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkAuditIntentDelivered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAuditIntentDelivered, id)
	return err
}

const markAuditIntentFailed = `-- name: MarkAuditIntentFailed :one
UPDATE audit_delivery_outbox
SET status = $2,
    available_at = $3,
    locked_at = NULL,
    last_error = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, event, status, attempt_count, max_attempts,
          available_at, locked_at, last_error, created_at, updated_at
`

type MarkAuditIntentFailedParams struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	LastError   pgtype.Text        `json:"last_error"`
}

func (q *Queries) MarkAuditIntentFailed(ctx context.Context, arg MarkAuditIntentFailedParams) (AuditDeliveryOutbox, error) {
	row := q.db.QueryRow(ctx, markAuditIntentFailed,
		arg.ID,
		arg.Status,
		arg.AvailableAt,
		arg.LastError,
	)
	var i AuditDeliveryOutbox
	err := row.Scan(
		&i.ID,
		&i.Event,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.AvailableAt,
		&i.LockedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
