// Code generated by sqlc-compatible query definitions. DO NOT EDIT.
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID              pgtype.UUID        `json:"id"`
	ActorUserID     pgtype.UUID        `json:"actor_user_id"`
	ActorType       string             `json:"actor_type"`
	Action          string             `json:"action"`
	ResourceType    pgtype.Text        `json:"resource_type"`
	ResourceID      pgtype.Text        `json:"resource_id"`
	StoryID         pgtype.UUID        `json:"story_id"`
	ChapterID       pgtype.UUID        `json:"chapter_id"`
	Result          string             `json:"result"`
	CorrelationID   pgtype.Text        `json:"correlation_id"`
	RequestID       pgtype.Text        `json:"request_id"`
	GenerationRunID pgtype.UUID        `json:"generation_run_id"`
	Provenance      []byte             `json:"provenance"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (
    id, actor_user_id, actor_type, action, resource_type, resource_id,
    story_id, chapter_id, result, correlation_id, request_id,
    generation_run_id, provenance, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, actor_user_id, actor_type, action, resource_type, resource_id,
          story_id, chapter_id, result, correlation_id, request_id,
          generation_run_id, provenance, metadata, created_at
`

type CreateAuditEventParams struct {
	ID              pgtype.UUID `json:"id"`
	ActorUserID     pgtype.UUID `json:"actor_user_id"`
	ActorType       string      `json:"actor_type"`
	Action          string      `json:"action"`
	ResourceType    pgtype.Text `json:"resource_type"`
	ResourceID      pgtype.Text `json:"resource_id"`
	StoryID         pgtype.UUID `json:"story_id"`
	ChapterID       pgtype.UUID `json:"chapter_id"`
	Result          string      `json:"result"`
	CorrelationID   pgtype.Text `json:"correlation_id"`
	RequestID       pgtype.Text `json:"request_id"`
	GenerationRunID pgtype.UUID `json:"generation_run_id"`
	Provenance      []byte      `json:"provenance"`
	Metadata        []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.ID, arg.ActorUserID, arg.ActorType, arg.Action, arg.ResourceType, arg.ResourceID,
		arg.StoryID, arg.ChapterID, arg.Result, arg.CorrelationID, arg.RequestID,
		arg.GenerationRunID, arg.Provenance, arg.Metadata,
	)
	return scanAuditEvent(row)
}

const getAuditEvent = `-- name: GetAuditEvent :one
SELECT id, actor_user_id, actor_type, action, resource_type, resource_id,
       story_id, chapter_id, result, correlation_id, request_id,
       generation_run_id, provenance, metadata, created_at
FROM audit_events
WHERE id = $1
`

func (q *Queries) GetAuditEvent(ctx context.Context, id pgtype.UUID) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, getAuditEvent, id)
	return scanAuditEvent(row)
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, actor_user_id, actor_type, action, resource_type, resource_id,
       story_id, chapter_id, result, correlation_id, request_id,
       generation_run_id, provenance, metadata, created_at
FROM audit_events
WHERE ($1::uuid IS NULL OR actor_user_id = $1)
  AND ($2::text IS NULL OR action = $2)
  AND ($3::text IS NULL OR resource_type = $3)
  AND ($4::text IS NULL OR resource_id = $4)
  AND ($5::uuid IS NULL OR story_id = $5)
  AND ($6::uuid IS NULL OR chapter_id = $6)
  AND ($7::uuid IS NULL OR generation_run_id = $7)
  AND ($8::text IS NULL OR correlation_id = $8)
  AND ($9::text IS NULL OR result = $9)
  AND ($10::timestamptz IS NULL OR created_at >= $10)
  AND ($11::timestamptz IS NULL OR created_at <= $11)
ORDER BY created_at DESC, id DESC
LIMIT $12
`

type ListAuditEventsParams struct {
	ActorUserID     pgtype.UUID        `json:"actor_user_id"`
	Action          pgtype.Text        `json:"action"`
	ResourceType    pgtype.Text        `json:"resource_type"`
	ResourceID      pgtype.Text        `json:"resource_id"`
	StoryID         pgtype.UUID        `json:"story_id"`
	ChapterID       pgtype.UUID        `json:"chapter_id"`
	GenerationRunID pgtype.UUID        `json:"generation_run_id"`
	CorrelationID   pgtype.Text        `json:"correlation_id"`
	Result          pgtype.Text        `json:"result"`
	CreatedFrom     pgtype.Timestamptz `json:"created_from"`
	CreatedTo       pgtype.Timestamptz `json:"created_to"`
	Limit           int32              `json:"limit"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.ActorUserID, arg.Action, arg.ResourceType, arg.ResourceID, arg.StoryID,
		arg.ChapterID, arg.GenerationRunID, arg.CorrelationID, arg.Result,
		arg.CreatedFrom, arg.CreatedTo, arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var item AuditEvent
		if err := rows.Scan(
			&item.ID, &item.ActorUserID, &item.ActorType, &item.Action, &item.ResourceType, &item.ResourceID,
			&item.StoryID, &item.ChapterID, &item.Result, &item.CorrelationID, &item.RequestID,
			&item.GenerationRunID, &item.Provenance, &item.Metadata, &item.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type auditEventScanner interface {
	Scan(dest ...any) error
}

func scanAuditEvent(row auditEventScanner) (AuditEvent, error) {
	var item AuditEvent
	err := row.Scan(
		&item.ID, &item.ActorUserID, &item.ActorType, &item.Action, &item.ResourceType, &item.ResourceID,
		&item.StoryID, &item.ChapterID, &item.Result, &item.CorrelationID, &item.RequestID,
		&item.GenerationRunID, &item.Provenance, &item.Metadata, &item.CreatedAt,
	)
	return item, err
}
