// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth_abuse.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const incrementAuthAbuseCounter = `-- name: IncrementAuthAbuseCounter :one
INSERT INTO auth_abuse_counters (scope, key_hash, window_start, count, updated_at)
VALUES ($1, $2, $3, 1, NOW())
ON CONFLICT (scope, key_hash, window_start)
DO UPDATE SET
    count = auth_abuse_counters.count + 1,
    updated_at = NOW()
RETURNING count
`

type IncrementAuthAbuseCounterParams struct {
	Scope       string             `json:"scope"`
	KeyHash     string             `json:"key_hash"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
}

func (q *Queries) IncrementAuthAbuseCounter(ctx context.Context, arg IncrementAuthAbuseCounterParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementAuthAbuseCounter, arg.Scope, arg.KeyHash, arg.WindowStart)
	var count int32
	err := row.Scan(&count)
	return count, err
}
