// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :one

INSERT INTO user_sessions (
    id, user_id, refresh_token_hash, created_at, last_used_at, expires_at,
    recent_auth_at, user_agent_summary, safe_ip_metadata
)
VALUES ($1, $2, $3, $4, $4, $5, $4, $6, $7)
RETURNING id, user_id, refresh_token_hash, created_at, last_used_at, expires_at,
          revoked_at, mfa_verified_at, recent_auth_at, user_agent_summary, safe_ip_metadata
`

type CreateAuthSessionParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	UserAgentSummary pgtype.Text        `json:"user_agent_summary"`
	SafeIpMetadata   pgtype.Text        `json:"safe_ip_metadata"`
}

// ============================================================
// V1 refresh session lifecycle
// ============================================================
func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.UserAgentSummary,
		arg.SafeIpMetadata,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.MfaVerifiedAt,
		&i.RecentAuthAt,
		&i.UserAgentSummary,
		&i.SafeIpMetadata,
	)
	return i, err
}

const listActiveAuthSessions = `-- name: ListActiveAuthSessions :many
SELECT id, user_id, refresh_token_hash, created_at, last_used_at, expires_at,
       revoked_at, mfa_verified_at, recent_auth_at, user_agent_summary, safe_ip_metadata
FROM user_sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > $2
  AND COALESCE(last_used_at, created_at) >= $3
ORDER BY last_used_at DESC NULLS LAST, created_at DESC
`

type ListActiveAuthSessionsParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) ListActiveAuthSessions(ctx context.Context, arg ListActiveAuthSessionsParams) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, listActiveAuthSessions, arg.UserID, arg.ExpiresAt, arg.LastUsedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSession{}
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.MfaVerifiedAt,
			&i.RecentAuthAt,
			&i.UserAgentSummary,
			&i.SafeIpMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAuthSessionByHash = `-- name: RevokeAuthSessionByHash :execrows
UPDATE user_sessions
SET revoked_at = NOW()
WHERE refresh_token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAuthSessionByHash(ctx context.Context, refreshTokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthSessionByHash, refreshTokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAuthSessionByIDForUser = `-- name: RevokeAuthSessionByIDForUser :execrows
UPDATE user_sessions
SET revoked_at = NOW()
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type RevokeAuthSessionByIDForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeAuthSessionByIDForUser(ctx context.Context, arg RevokeAuthSessionByIDForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthSessionByIDForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateAuthSession = `-- name: RotateAuthSession :one
UPDATE user_sessions
SET refresh_token_hash = $2,
    last_used_at = $3
WHERE refresh_token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > $3
  AND COALESCE(last_used_at, created_at) >= $4
RETURNING id, user_id, refresh_token_hash, created_at, last_used_at, expires_at,
          revoked_at, mfa_verified_at, recent_auth_at, user_agent_summary, safe_ip_metadata
`

type RotateAuthSessionParams struct {
	RefreshTokenHash   string             `json:"refresh_token_hash"`
	RefreshTokenHash_2 string             `json:"refresh_token_hash_2"`
	LastUsedAt         pgtype.Timestamptz `json:"last_used_at"`
	LastUsedAt_2       pgtype.Timestamptz `json:"last_used_at_2"`
}

func (q *Queries) RotateAuthSession(ctx context.Context, arg RotateAuthSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, rotateAuthSession,
		arg.RefreshTokenHash,
		arg.RefreshTokenHash_2,
		arg.LastUsedAt,
		arg.LastUsedAt_2,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.MfaVerifiedAt,
		&i.RecentAuthAt,
		&i.UserAgentSummary,
		&i.SafeIpMetadata,
	)
	return i, err
}

const touchAuthSession = `-- name: TouchAuthSession :one
UPDATE user_sessions
SET last_used_at = $2
WHERE id = $1
  AND revoked_at IS NULL
  AND expires_at > $2
  AND COALESCE(last_used_at, created_at) >= $3
RETURNING id, user_id, refresh_token_hash, created_at, last_used_at, expires_at,
          revoked_at, mfa_verified_at, recent_auth_at, user_agent_summary, safe_ip_metadata
`

type TouchAuthSessionParams struct {
	ID           pgtype.UUID        `json:"id"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	LastUsedAt_2 pgtype.Timestamptz `json:"last_used_at_2"`
}

func (q *Queries) TouchAuthSession(ctx context.Context, arg TouchAuthSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, touchAuthSession, arg.ID, arg.LastUsedAt, arg.LastUsedAt_2)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.MfaVerifiedAt,
		&i.RecentAuthAt,
		&i.UserAgentSummary,
		&i.SafeIpMetadata,
	)
	return i, err
}
