// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: foundation.sql

package db

import (
	"context"
)

const pingBootstrap = `-- name: PingBootstrap :one
SELECT id, created_at
FROM schema_bootstrap
WHERE id = TRUE
`

// Foundation placeholder query used to verify sqlc generation wiring.
func (q *Queries) PingBootstrap(ctx context.Context) (SchemaBootstrap, error) {
	row := q.db.QueryRow(ctx, pingBootstrap)
	var i SchemaBootstrap
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
