// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelJob = `-- name: CancelJob :one
UPDATE generation_jobs
SET status = 'CANCELLED',
    completed_at = NOW(),
    locked_by = NULL,
    lock_expires_at = NULL
WHERE id = $1
RETURNING id, run_id, job_type, status, priority, available_at, input_fingerprint,
          attempt_count, max_attempts, locked_by, lock_expires_at, started_at,
          completed_at, last_error_class, last_error_code, output_ref, created_at
`

func (q *Queries) CancelJob(ctx context.Context, id pgtype.UUID) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, cancelJob, id)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobType,
		&i.Status,
		&i.Priority,
		&i.AvailableAt,
		&i.InputFingerprint,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastErrorClass,
		&i.LastErrorCode,
		&i.OutputRef,
		&i.CreatedAt,
	)
	return i, err
}

const claimNextJob = `-- name: ClaimNextJob :one
UPDATE generation_jobs
SET status = 'RUNNING',
    locked_by = $1,
    lock_expires_at = NOW() + INTERVAL '5 minutes',
    started_at = NOW(),
    attempt_count = attempt_count + 1
WHERE id = (
    SELECT id
    FROM generation_jobs
    WHERE status = 'PENDING'
      AND available_at <= NOW()
    ORDER BY priority DESC, created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, run_id, job_type, status, priority, available_at, input_fingerprint,
          attempt_count, max_attempts, locked_by, lock_expires_at, started_at,
          completed_at, last_error_class, last_error_code, output_ref, created_at
`

func (q *Queries) ClaimNextJob(ctx context.Context, lockedBy pgtype.Text) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, claimNextJob, lockedBy)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobType,
		&i.Status,
		&i.Priority,
		&i.AvailableAt,
		&i.InputFingerprint,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastErrorClass,
		&i.LastErrorCode,
		&i.OutputRef,
		&i.CreatedAt,
	)
	return i, err
}

const createChapterReview = `-- name: CreateChapterReview :one

INSERT INTO chapter_reviews (id, chapter_id, content_revision_id, review_type,
                             canon_version_id, policy_version_id, outcome, report,
                             generation_run_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, chapter_id, content_revision_id, review_type, canon_version_id,
          policy_version_id, outcome, report, generation_run_id, created_at
`

type CreateChapterReviewParams struct {
	ID                pgtype.UUID `json:"id"`
	ChapterID         pgtype.UUID `json:"chapter_id"`
	ContentRevisionID pgtype.UUID `json:"content_revision_id"`
	ReviewType        string      `json:"review_type"`
	CanonVersionID    pgtype.UUID `json:"canon_version_id"`
	PolicyVersionID   pgtype.UUID `json:"policy_version_id"`
	Outcome           string      `json:"outcome"`
	Report            []byte      `json:"report"`
	GenerationRunID   pgtype.UUID `json:"generation_run_id"`
}

// ============================================================
// Chapter Reviews
// ============================================================
func (q *Queries) CreateChapterReview(ctx context.Context, arg CreateChapterReviewParams) (ChapterReview, error) {
	row := q.db.QueryRow(ctx, createChapterReview,
		arg.ID,
		arg.ChapterID,
		arg.ContentRevisionID,
		arg.ReviewType,
		arg.CanonVersionID,
		arg.PolicyVersionID,
		arg.Outcome,
		arg.Report,
		arg.GenerationRunID,
	)
	var i ChapterReview
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.ContentRevisionID,
		&i.ReviewType,
		&i.CanonVersionID,
		&i.PolicyVersionID,
		&i.Outcome,
		&i.Report,
		&i.GenerationRunID,
		&i.CreatedAt,
	)
	return i, err
}

const createContentApproval = `-- name: CreateContentApproval :one
INSERT INTO content_approvals (id, chapter_id, content_revision_id, approved_by,
                               warnings_snapshot, override_snapshot)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, chapter_id, content_revision_id, approved_by, approved_at,
          warnings_snapshot, override_snapshot
`

type CreateContentApprovalParams struct {
	ID                pgtype.UUID `json:"id"`
	ChapterID         pgtype.UUID `json:"chapter_id"`
	ContentRevisionID pgtype.UUID `json:"content_revision_id"`
	ApprovedBy        pgtype.UUID `json:"approved_by"`
	WarningsSnapshot  []byte      `json:"warnings_snapshot"`
	OverrideSnapshot  []byte      `json:"override_snapshot"`
}

func (q *Queries) CreateContentApproval(ctx context.Context, arg CreateContentApprovalParams) (ContentApproval, error) {
	row := q.db.QueryRow(ctx, createContentApproval,
		arg.ID,
		arg.ChapterID,
		arg.ContentRevisionID,
		arg.ApprovedBy,
		arg.WarningsSnapshot,
		arg.OverrideSnapshot,
	)
	var i ContentApproval
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.ContentRevisionID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.WarningsSnapshot,
		&i.OverrideSnapshot,
	)
	return i, err
}

const createContentRevision = `-- name: CreateContentRevision :one
INSERT INTO chapter_content_revisions (id, chapter_id, revision_no, content_text, source_type,
                                       based_on_revision_id, plan_revision_id,
                                       base_canon_version_id, generation_run_id,
                                       retcon_request_id, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, chapter_id, revision_no, content_text, source_type, based_on_revision_id,
          plan_revision_id, base_canon_version_id, generation_run_id, retcon_request_id,
          status, created_by, created_at
`

type CreateContentRevisionParams struct {
	ID                 pgtype.UUID `json:"id"`
	ChapterID          pgtype.UUID `json:"chapter_id"`
	RevisionNo         int32       `json:"revision_no"`
	ContentText        string      `json:"content_text"`
	SourceType         string      `json:"source_type"`
	BasedOnRevisionID  pgtype.UUID `json:"based_on_revision_id"`
	PlanRevisionID     pgtype.UUID `json:"plan_revision_id"`
	BaseCanonVersionID pgtype.UUID `json:"base_canon_version_id"`
	GenerationRunID    pgtype.UUID `json:"generation_run_id"`
	RetconRequestID    pgtype.UUID `json:"retcon_request_id"`
	Status             string      `json:"status"`
	CreatedBy          pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateContentRevision(ctx context.Context, arg CreateContentRevisionParams) (ChapterContentRevision, error) {
	row := q.db.QueryRow(ctx, createContentRevision,
		arg.ID,
		arg.ChapterID,
		arg.RevisionNo,
		arg.ContentText,
		arg.SourceType,
		arg.BasedOnRevisionID,
		arg.PlanRevisionID,
		arg.BaseCanonVersionID,
		arg.GenerationRunID,
		arg.RetconRequestID,
		arg.Status,
		arg.CreatedBy,
	)
	var i ChapterContentRevision
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.RevisionNo,
		&i.ContentText,
		&i.SourceType,
		&i.BasedOnRevisionID,
		&i.PlanRevisionID,
		&i.BaseCanonVersionID,
		&i.GenerationRunID,
		&i.RetconRequestID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createGenerationJob = `-- name: CreateGenerationJob :one

INSERT INTO generation_jobs (id, run_id, job_type, status, priority, available_at,
                             input_fingerprint, attempt_count, max_attempts)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, run_id, job_type, status, priority, available_at, input_fingerprint,
          attempt_count, max_attempts, locked_by, lock_expires_at, started_at,
          completed_at, last_error_class, last_error_code, output_ref, created_at
`

type CreateGenerationJobParams struct {
	ID               pgtype.UUID        `json:"id"`
	RunID            pgtype.UUID        `json:"run_id"`
	JobType          string             `json:"job_type"`
	Status           string             `json:"status"`
	Priority         int32              `json:"priority"`
	AvailableAt      pgtype.Timestamptz `json:"available_at"`
	InputFingerprint pgtype.Text        `json:"input_fingerprint"`
	AttemptCount     int32              `json:"attempt_count"`
	MaxAttempts      int32              `json:"max_attempts"`
}

// ============================================================
// Generation Jobs
// ============================================================
func (q *Queries) CreateGenerationJob(ctx context.Context, arg CreateGenerationJobParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, createGenerationJob,
		arg.ID,
		arg.RunID,
		arg.JobType,
		arg.Status,
		arg.Priority,
		arg.AvailableAt,
		arg.InputFingerprint,
		arg.AttemptCount,
		arg.MaxAttempts,
	)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobType,
		&i.Status,
		&i.Priority,
		&i.AvailableAt,
		&i.InputFingerprint,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastErrorClass,
		&i.LastErrorCode,
		&i.OutputRef,
		&i.CreatedAt,
	)
	return i, err
}

const createGenerationRun = `-- name: CreateGenerationRun :one

INSERT INTO generation_runs (id, run_type, story_id, chapter_id, status, waiting_reason,
                             workflow_version, priority, base_canon_version_id,
                             context_snapshot_id, requested_by, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, run_type, story_id, chapter_id, status, waiting_reason, workflow_version,
          priority, base_canon_version_id, context_snapshot_id, requested_by,
          idempotency_key, started_at, completed_at, created_at
`

type CreateGenerationRunParams struct {
	ID                 pgtype.UUID `json:"id"`
	RunType            string      `json:"run_type"`
	StoryID            pgtype.UUID `json:"story_id"`
	ChapterID          pgtype.UUID `json:"chapter_id"`
	Status             string      `json:"status"`
	WaitingReason      pgtype.Text `json:"waiting_reason"`
	WorkflowVersion    pgtype.Text `json:"workflow_version"`
	Priority           int32       `json:"priority"`
	BaseCanonVersionID pgtype.UUID `json:"base_canon_version_id"`
	ContextSnapshotID  pgtype.UUID `json:"context_snapshot_id"`
	RequestedBy        pgtype.UUID `json:"requested_by"`
	IdempotencyKey     pgtype.Text `json:"idempotency_key"`
}

// ============================================================
// Generation Runs
// ============================================================
func (q *Queries) CreateGenerationRun(ctx context.Context, arg CreateGenerationRunParams) (GenerationRun, error) {
	row := q.db.QueryRow(ctx, createGenerationRun,
		arg.ID,
		arg.RunType,
		arg.StoryID,
		arg.ChapterID,
		arg.Status,
		arg.WaitingReason,
		arg.WorkflowVersion,
		arg.Priority,
		arg.BaseCanonVersionID,
		arg.ContextSnapshotID,
		arg.RequestedBy,
		arg.IdempotencyKey,
	)
	var i GenerationRun
	err := row.Scan(
		&i.ID,
		&i.RunType,
		&i.StoryID,
		&i.ChapterID,
		&i.Status,
		&i.WaitingReason,
		&i.WorkflowVersion,
		&i.Priority,
		&i.BaseCanonVersionID,
		&i.ContextSnapshotID,
		&i.RequestedBy,
		&i.IdempotencyKey,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createJobAttempt = `-- name: CreateJobAttempt :one
INSERT INTO generation_job_attempts (id, job_id, attempt_no, provider, model, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, job_id, attempt_no, provider, model, status, error_class, error_code,
          safe_error_detail, usage, latency_ms, started_at, completed_at
`

type CreateJobAttemptParams struct {
	ID        pgtype.UUID `json:"id"`
	JobID     pgtype.UUID `json:"job_id"`
	AttemptNo int32       `json:"attempt_no"`
	Provider  pgtype.Text `json:"provider"`
	Model     pgtype.Text `json:"model"`
	Status    string      `json:"status"`
}

func (q *Queries) CreateJobAttempt(ctx context.Context, arg CreateJobAttemptParams) (GenerationJobAttempt, error) {
	row := q.db.QueryRow(ctx, createJobAttempt,
		arg.ID,
		arg.JobID,
		arg.AttemptNo,
		arg.Provider,
		arg.Model,
		arg.Status,
	)
	var i GenerationJobAttempt
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptNo,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.ErrorClass,
		&i.ErrorCode,
		&i.SafeErrorDetail,
		&i.Usage,
		&i.LatencyMs,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getContentRevision = `-- name: GetContentRevision :one
SELECT id, chapter_id, revision_no, content_text, source_type, based_on_revision_id,
       plan_revision_id, base_canon_version_id, generation_run_id, retcon_request_id,
       status, created_by, created_at
FROM chapter_content_revisions
WHERE id = $1
`

func (q *Queries) GetContentRevision(ctx context.Context, id pgtype.UUID) (ChapterContentRevision, error) {
	row := q.db.QueryRow(ctx, getContentRevision, id)
	var i ChapterContentRevision
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.RevisionNo,
		&i.ContentText,
		&i.SourceType,
		&i.BasedOnRevisionID,
		&i.PlanRevisionID,
		&i.BaseCanonVersionID,
		&i.GenerationRunID,
		&i.RetconRequestID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGenerationRun = `-- name: GetGenerationRun :one
SELECT id, run_type, story_id, chapter_id, status, waiting_reason, workflow_version,
       priority, base_canon_version_id, context_snapshot_id, requested_by,
       idempotency_key, started_at, completed_at, created_at
FROM generation_runs
WHERE id = $1
`

func (q *Queries) GetGenerationRun(ctx context.Context, id pgtype.UUID) (GenerationRun, error) {
	row := q.db.QueryRow(ctx, getGenerationRun, id)
	var i GenerationRun
	err := row.Scan(
		&i.ID,
		&i.RunType,
		&i.StoryID,
		&i.ChapterID,
		&i.Status,
		&i.WaitingReason,
		&i.WorkflowVersion,
		&i.Priority,
		&i.BaseCanonVersionID,
		&i.ContextSnapshotID,
		&i.RequestedBy,
		&i.IdempotencyKey,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listChapterReviews = `-- name: ListChapterReviews :many
SELECT id, chapter_id, content_revision_id, review_type, canon_version_id,
       policy_version_id, outcome, report, generation_run_id, created_at
FROM chapter_reviews
WHERE chapter_id = $1
ORDER BY created_at
`

func (q *Queries) ListChapterReviews(ctx context.Context, chapterID pgtype.UUID) ([]ChapterReview, error) {
	rows, err := q.db.Query(ctx, listChapterReviews, chapterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChapterReview{}
	for rows.Next() {
		var i ChapterReview
		if err := rows.Scan(
			&i.ID,
			&i.ChapterID,
			&i.ContentRevisionID,
			&i.ReviewType,
			&i.CanonVersionID,
			&i.PolicyVersionID,
			&i.Outcome,
			&i.Report,
			&i.GenerationRunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentRevisions = `-- name: ListContentRevisions :many
SELECT id, chapter_id, revision_no, content_text, source_type, based_on_revision_id,
       plan_revision_id, base_canon_version_id, generation_run_id, retcon_request_id,
       status, created_by, created_at
FROM chapter_content_revisions
WHERE chapter_id = $1
ORDER BY revision_no
`

func (q *Queries) ListContentRevisions(ctx context.Context, chapterID pgtype.UUID) ([]ChapterContentRevision, error) {
	rows, err := q.db.Query(ctx, listContentRevisions, chapterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChapterContentRevision{}
	for rows.Next() {
		var i ChapterContentRevision
		if err := rows.Scan(
			&i.ID,
			&i.ChapterID,
			&i.RevisionNo,
			&i.ContentText,
			&i.SourceType,
			&i.BasedOnRevisionID,
			&i.PlanRevisionID,
			&i.BaseCanonVersionID,
			&i.GenerationRunID,
			&i.RetconRequestID,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAttemptNo = `-- name: NextAttemptNo :one
SELECT COALESCE(MAX(attempt_no), 0) + 1
FROM generation_job_attempts
WHERE job_id = $1
`

func (q *Queries) NextAttemptNo(ctx context.Context, jobID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextAttemptNo, jobID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextContentRevision = `-- name: NextContentRevision :one

SELECT COALESCE(MAX(revision_no), 0) + 1
FROM chapter_content_revisions
WHERE chapter_id = $1
`

// ============================================================
// Chapter Content Revisions
// ============================================================
func (q *Queries) NextContentRevision(ctx context.Context, chapterID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextContentRevision, chapterID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const reclaimStaleJobs = `-- name: ReclaimStaleJobs :many
UPDATE generation_jobs
SET status = 'PENDING',
    locked_by = NULL,
    lock_expires_at = NULL
WHERE status = 'RUNNING'
  AND lock_expires_at < NOW()
RETURNING id, run_id, job_type, status, priority, available_at, input_fingerprint,
          attempt_count, max_attempts, locked_by, lock_expires_at, started_at,
          completed_at, last_error_class, last_error_code, output_ref, created_at
`

func (q *Queries) ReclaimStaleJobs(ctx context.Context) ([]GenerationJob, error) {
	rows, err := q.db.Query(ctx, reclaimStaleJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GenerationJob{}
	for rows.Next() {
		var i GenerationJob
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobType,
			&i.Status,
			&i.Priority,
			&i.AvailableAt,
			&i.InputFingerprint,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.LockedBy,
			&i.LockExpiresAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LastErrorClass,
			&i.LastErrorCode,
			&i.OutputRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContentRevisionStatus = `-- name: UpdateContentRevisionStatus :one
UPDATE chapter_content_revisions
SET status = $2
WHERE id = $1
RETURNING id, chapter_id, revision_no, content_text, source_type, based_on_revision_id,
          plan_revision_id, base_canon_version_id, generation_run_id, retcon_request_id,
          status, created_by, created_at
`

type UpdateContentRevisionStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateContentRevisionStatus(ctx context.Context, arg UpdateContentRevisionStatusParams) (ChapterContentRevision, error) {
	row := q.db.QueryRow(ctx, updateContentRevisionStatus, arg.ID, arg.Status)
	var i ChapterContentRevision
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.RevisionNo,
		&i.ContentText,
		&i.SourceType,
		&i.BasedOnRevisionID,
		&i.PlanRevisionID,
		&i.BaseCanonVersionID,
		&i.GenerationRunID,
		&i.RetconRequestID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateJobAttemptStatus = `-- name: UpdateJobAttemptStatus :one
UPDATE generation_job_attempts
SET status = $2,
    error_class = $3,
    error_code = $4,
    completed_at = CASE WHEN $2 IN ('SUCCEEDED', 'FAILED') THEN NOW() ELSE completed_at END
WHERE id = $1
RETURNING id, job_id, attempt_no, provider, model, status, error_class, error_code,
          safe_error_detail, usage, latency_ms, started_at, completed_at
`

type UpdateJobAttemptStatusParams struct {
	ID         pgtype.UUID `json:"id"`
	Status     string      `json:"status"`
	ErrorClass pgtype.Text `json:"error_class"`
	ErrorCode  pgtype.Text `json:"error_code"`
}

func (q *Queries) UpdateJobAttemptStatus(ctx context.Context, arg UpdateJobAttemptStatusParams) (GenerationJobAttempt, error) {
	row := q.db.QueryRow(ctx, updateJobAttemptStatus,
		arg.ID,
		arg.Status,
		arg.ErrorClass,
		arg.ErrorCode,
	)
	var i GenerationJobAttempt
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptNo,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.ErrorClass,
		&i.ErrorCode,
		&i.SafeErrorDetail,
		&i.Usage,
		&i.LatencyMs,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE generation_jobs
SET status = $2,
    last_error_class = $3,
    last_error_code = $4,
    completed_at = CASE WHEN $2 IN ('SUCCEEDED', 'FAILED', 'CANCELLED') THEN NOW() ELSE completed_at END,
    locked_by = NULL,
    lock_expires_at = NULL
WHERE id = $1
RETURNING id, run_id, job_type, status, priority, available_at, input_fingerprint,
          attempt_count, max_attempts, locked_by, lock_expires_at, started_at,
          completed_at, last_error_class, last_error_code, output_ref, created_at
`

type UpdateJobStatusParams struct {
	ID             pgtype.UUID `json:"id"`
	Status         string      `json:"status"`
	LastErrorClass pgtype.Text `json:"last_error_class"`
	LastErrorCode  pgtype.Text `json:"last_error_code"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, updateJobStatus,
		arg.ID,
		arg.Status,
		arg.LastErrorClass,
		arg.LastErrorCode,
	)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobType,
		&i.Status,
		&i.Priority,
		&i.AvailableAt,
		&i.InputFingerprint,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastErrorClass,
		&i.LastErrorCode,
		&i.OutputRef,
		&i.CreatedAt,
	)
	return i, err
}
