// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: identity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmMFAMethod = `-- name: ConfirmMFAMethod :exec
UPDATE user_mfa_methods SET confirmed_at = NOW() WHERE user_id = $1 AND confirmed_at IS NULL
`

func (q *Queries) ConfirmMFAMethod(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, confirmMFAMethod, userID)
	return err
}

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT COUNT(*)
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
JOIN users u ON u.id = ur.user_id
WHERE r.code = 'ADMIN' AND u.status = 'ACTIVE'
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO user_sessions (id, user_id, refresh_token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash, display_name, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, display_name, status, email_verified_at, created_at, updated_at, deactivated_at
`

type CreateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	DisplayName  pgtype.Text `json:"display_name"`
	Status       string      `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET status = 'DEACTIVATED', deactivated_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const disableMFAMethod = `-- name: DisableMFAMethod :exec
UPDATE user_mfa_methods SET disabled_at = NOW() WHERE user_id = $1 AND disabled_at IS NULL
`

func (q *Queries) DisableMFAMethod(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableMFAMethod, userID)
	return err
}

const getMFAMethod = `-- name: GetMFAMethod :one
SELECT id, user_id, type, encrypted_secret, confirmed_at, disabled_at
FROM user_mfa_methods
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetMFAMethod(ctx context.Context, userID pgtype.UUID) (UserMfaMethod, error) {
	row := q.db.QueryRow(ctx, getMFAMethod, userID)
	var i UserMfaMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.EncryptedSecret,
		&i.ConfirmedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getResetToken = `-- name: GetResetToken :one
SELECT token_hash
FROM password_reset_tokens
WHERE user_id = $1 AND used_at IS NULL AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetResetToken(ctx context.Context, userID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getResetToken, userID)
	var token_hash string
	err := row.Scan(&token_hash)
	return token_hash, err
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT p.code
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
JOIN roles r ON r.id = rp.role_id
WHERE r.code = $1
`

func (q *Queries) GetRolePermissions(ctx context.Context, code string) ([]string, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, status, email_verified_at, created_at, updated_at, deactivated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, status, email_verified_at, created_at, updated_at, deactivated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.code
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVerificationToken = `-- name: GetVerificationToken :one
SELECT token_hash
FROM email_verification_tokens
WHERE user_id = $1 AND used_at IS NULL AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetVerificationToken(ctx context.Context, userID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getVerificationToken, userID)
	var token_hash string
	err := row.Scan(&token_hash)
	return token_hash, err
}

const grantRole = `-- name: GrantRole :exec
INSERT INTO user_roles (user_id, role_id)
SELECT $1, id FROM roles WHERE code = $2
ON CONFLICT (user_id, role_id) DO NOTHING
`

type GrantRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Code   string      `json:"code"`
}

func (q *Queries) GrantRole(ctx context.Context, arg GrantRoleParams) error {
	_, err := q.db.Exec(ctx, grantRole, arg.UserID, arg.Code)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users SET email_verified_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const purgeUser = `-- name: PurgeUser :exec
UPDATE users SET email = 'deleted-' || id::text || '@deleted.invalid', password_hash = NULL, display_name = NULL, updated_at = NOW() WHERE id = $1
`

func (q *Queries) PurgeUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, purgeUser, id)
	return err
}

const reactivateUser = `-- name: ReactivateUser :exec
UPDATE users SET status = 'ACTIVE', deactivated_at = NULL, updated_at = NOW() WHERE id = $1
`

func (q *Queries) ReactivateUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, reactivateUser, id)
	return err
}

const revokeRole = `-- name: RevokeRole :exec
DELETE FROM user_roles
WHERE user_id = $1 AND role_id = (SELECT id FROM roles WHERE code = $2)
`

type RevokeRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Code   string      `json:"code"`
}

func (q *Queries) RevokeRole(ctx context.Context, arg RevokeRoleParams) error {
	_, err := q.db.Exec(ctx, revokeRole, arg.UserID, arg.Code)
	return err
}

const revokeSessions = `-- name: RevokeSessions :exec
UPDATE user_sessions SET revoked_at = NOW() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSessions, userID)
	return err
}

const storeMFAMethod = `-- name: StoreMFAMethod :exec
INSERT INTO user_mfa_methods (id, user_id, type, encrypted_secret)
VALUES (gen_random_uuid(), $1, 'TOTP', $2)
`

type StoreMFAMethodParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	EncryptedSecret string      `json:"encrypted_secret"`
}

func (q *Queries) StoreMFAMethod(ctx context.Context, arg StoreMFAMethodParams) error {
	_, err := q.db.Exec(ctx, storeMFAMethod, arg.UserID, arg.EncryptedSecret)
	return err
}

const storeResetToken = `-- name: StoreResetToken :exec
INSERT INTO password_reset_tokens (id, user_id, token_hash, expires_at)
VALUES (gen_random_uuid(), $1, $2, NOW() + INTERVAL '1 hour')
`

type StoreResetTokenParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	TokenHash string      `json:"token_hash"`
}

func (q *Queries) StoreResetToken(ctx context.Context, arg StoreResetTokenParams) error {
	_, err := q.db.Exec(ctx, storeResetToken, arg.UserID, arg.TokenHash)
	return err
}

const storeVerificationToken = `-- name: StoreVerificationToken :exec
INSERT INTO email_verification_tokens (id, user_id, token_hash, expires_at)
VALUES (gen_random_uuid(), $1, $2, NOW() + INTERVAL '24 hours')
`

type StoreVerificationTokenParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	TokenHash string      `json:"token_hash"`
}

func (q *Queries) StoreVerificationToken(ctx context.Context, arg StoreVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, storeVerificationToken, arg.UserID, arg.TokenHash)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}
