// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: listener.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec

INSERT INTO favorites (user_id, story_id)
VALUES ($1, $2)
ON CONFLICT (user_id, story_id) DO NOTHING
`

type AddFavoriteParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	StoryID pgtype.UUID `json:"story_id"`
}

// ============================================================
// Favorites
// ============================================================
func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.StoryID)
	return err
}

const applyRelistenStatus = `-- name: ApplyRelistenStatus :many
UPDATE listening_progress
SET relisten_status = $2,
    updated_at = NOW()
WHERE chapter_id = $1
RETURNING user_id, chapter_id, position_ms, completed_at, last_audio_asset_id,
          last_playback_session_id, version, relisten_status, last_listened_at, updated_at
`

type ApplyRelistenStatusParams struct {
	ChapterID      pgtype.UUID `json:"chapter_id"`
	RelistenStatus string      `json:"relisten_status"`
}

type ApplyRelistenStatusRow struct {
	UserID                pgtype.UUID        `json:"user_id"`
	ChapterID             pgtype.UUID        `json:"chapter_id"`
	PositionMs            int64              `json:"position_ms"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	LastAudioAssetID      pgtype.UUID        `json:"last_audio_asset_id"`
	LastPlaybackSessionID pgtype.UUID        `json:"last_playback_session_id"`
	Version               int64              `json:"version"`
	RelistenStatus        string             `json:"relisten_status"`
	LastListenedAt        pgtype.Timestamptz `json:"last_listened_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ApplyRelistenStatus(ctx context.Context, arg ApplyRelistenStatusParams) ([]ApplyRelistenStatusRow, error) {
	rows, err := q.db.Query(ctx, applyRelistenStatus, arg.ChapterID, arg.RelistenStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplyRelistenStatusRow{}
	for rows.Next() {
		var i ApplyRelistenStatusRow
		if err := rows.Scan(
			&i.UserID,
			&i.ChapterID,
			&i.PositionMs,
			&i.CompletedAt,
			&i.LastAudioAssetID,
			&i.LastPlaybackSessionID,
			&i.Version,
			&i.RelistenStatus,
			&i.LastListenedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProgress = `-- name: GetProgress :one

SELECT user_id, chapter_id, position_ms, completed_at, last_audio_asset_id,
       last_playback_session_id, version, relisten_status, last_listened_at, updated_at
FROM listening_progress
WHERE user_id = $1 AND chapter_id = $2
`

type GetProgressParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ChapterID pgtype.UUID `json:"chapter_id"`
}

type GetProgressRow struct {
	UserID                pgtype.UUID        `json:"user_id"`
	ChapterID             pgtype.UUID        `json:"chapter_id"`
	PositionMs            int64              `json:"position_ms"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	LastAudioAssetID      pgtype.UUID        `json:"last_audio_asset_id"`
	LastPlaybackSessionID pgtype.UUID        `json:"last_playback_session_id"`
	Version               int64              `json:"version"`
	RelistenStatus        string             `json:"relisten_status"`
	LastListenedAt        pgtype.Timestamptz `json:"last_listened_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// ============================================================
// Listening Progress
// ============================================================
func (q *Queries) GetProgress(ctx context.Context, arg GetProgressParams) (GetProgressRow, error) {
	row := q.db.QueryRow(ctx, getProgress, arg.UserID, arg.ChapterID)
	var i GetProgressRow
	err := row.Scan(
		&i.UserID,
		&i.ChapterID,
		&i.PositionMs,
		&i.CompletedAt,
		&i.LastAudioAssetID,
		&i.LastPlaybackSessionID,
		&i.Version,
		&i.RelistenStatus,
		&i.LastListenedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isFavorite = `-- name: IsFavorite :one
SELECT EXISTS(SELECT 1 FROM favorites WHERE user_id = $1 AND story_id = $2)
`

type IsFavoriteParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	StoryID pgtype.UUID `json:"story_id"`
}

func (q *Queries) IsFavorite(ctx context.Context, arg IsFavoriteParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFavorite, arg.UserID, arg.StoryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFavorites = `-- name: ListFavorites :many
SELECT user_id, story_id, created_at
FROM favorites
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFavorites(ctx context.Context, userID pgtype.UUID) ([]Favorite, error) {
	rows, err := q.db.Query(ctx, listFavorites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Favorite{}
	for rows.Next() {
		var i Favorite
		if err := rows.Scan(&i.UserID, &i.StoryID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCompleted = `-- name: MarkCompleted :one
UPDATE listening_progress
SET completed_at = NOW(),
    updated_at = NOW()
WHERE user_id = $1 AND chapter_id = $2
RETURNING user_id, chapter_id, position_ms, completed_at, last_audio_asset_id,
          last_playback_session_id, version, relisten_status, last_listened_at, updated_at
`

type MarkCompletedParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ChapterID pgtype.UUID `json:"chapter_id"`
}

type MarkCompletedRow struct {
	UserID                pgtype.UUID        `json:"user_id"`
	ChapterID             pgtype.UUID        `json:"chapter_id"`
	PositionMs            int64              `json:"position_ms"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	LastAudioAssetID      pgtype.UUID        `json:"last_audio_asset_id"`
	LastPlaybackSessionID pgtype.UUID        `json:"last_playback_session_id"`
	Version               int64              `json:"version"`
	RelistenStatus        string             `json:"relisten_status"`
	LastListenedAt        pgtype.Timestamptz `json:"last_listened_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkCompleted(ctx context.Context, arg MarkCompletedParams) (MarkCompletedRow, error) {
	row := q.db.QueryRow(ctx, markCompleted, arg.UserID, arg.ChapterID)
	var i MarkCompletedRow
	err := row.Scan(
		&i.UserID,
		&i.ChapterID,
		&i.PositionMs,
		&i.CompletedAt,
		&i.LastAudioAssetID,
		&i.LastPlaybackSessionID,
		&i.Version,
		&i.RelistenStatus,
		&i.LastListenedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites
WHERE user_id = $1 AND story_id = $2
`

type RemoveFavoriteParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	StoryID pgtype.UUID `json:"story_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.StoryID)
	return err
}

const saveProgress = `-- name: SaveProgress :one
INSERT INTO listening_progress (user_id, chapter_id, position_ms, last_audio_asset_id,
                                last_playback_session_id, version, last_listened_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (user_id, chapter_id)
DO UPDATE SET position_ms = EXCLUDED.position_ms,
              last_audio_asset_id = EXCLUDED.last_audio_asset_id,
              last_playback_session_id = EXCLUDED.last_playback_session_id,
              version = EXCLUDED.version,
              last_listened_at = NOW(),
              updated_at = NOW()
RETURNING user_id, chapter_id, position_ms, completed_at, last_audio_asset_id,
          last_playback_session_id, version, relisten_status, last_listened_at, updated_at
`

type SaveProgressParams struct {
	UserID                pgtype.UUID `json:"user_id"`
	ChapterID             pgtype.UUID `json:"chapter_id"`
	PositionMs            int64       `json:"position_ms"`
	LastAudioAssetID      pgtype.UUID `json:"last_audio_asset_id"`
	LastPlaybackSessionID pgtype.UUID `json:"last_playback_session_id"`
	Version               int64       `json:"version"`
}

type SaveProgressRow struct {
	UserID                pgtype.UUID        `json:"user_id"`
	ChapterID             pgtype.UUID        `json:"chapter_id"`
	PositionMs            int64              `json:"position_ms"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	LastAudioAssetID      pgtype.UUID        `json:"last_audio_asset_id"`
	LastPlaybackSessionID pgtype.UUID        `json:"last_playback_session_id"`
	Version               int64              `json:"version"`
	RelistenStatus        string             `json:"relisten_status"`
	LastListenedAt        pgtype.Timestamptz `json:"last_listened_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SaveProgress(ctx context.Context, arg SaveProgressParams) (SaveProgressRow, error) {
	row := q.db.QueryRow(ctx, saveProgress,
		arg.UserID,
		arg.ChapterID,
		arg.PositionMs,
		arg.LastAudioAssetID,
		arg.LastPlaybackSessionID,
		arg.Version,
	)
	var i SaveProgressRow
	err := row.Scan(
		&i.UserID,
		&i.ChapterID,
		&i.PositionMs,
		&i.CompletedAt,
		&i.LastAudioAssetID,
		&i.LastPlaybackSessionID,
		&i.Version,
		&i.RelistenStatus,
		&i.LastListenedAt,
		&i.UpdatedAt,
	)
	return i, err
}
