// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaBootstrap struct {
	ID        bool               `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
