// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountDeletionRequest struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
	PurgeAfter  pgtype.Timestamptz `json:"purge_after"`
	CancelledAt pgtype.Timestamptz `json:"cancelled_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type CanonBranch struct {
	ID              pgtype.UUID        `json:"id"`
	StoryID         pgtype.UUID        `json:"story_id"`
	Type            string             `json:"type"`
	Status          string             `json:"status"`
	BaseVersionID   pgtype.UUID        `json:"base_version_id"`
	GenerationRunID pgtype.UUID        `json:"generation_run_id"`
	RetconRequestID pgtype.UUID        `json:"retcon_request_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type CanonChangeItem struct {
	ID             pgtype.UUID `json:"id"`
	CanonVersionID pgtype.UUID `json:"canon_version_id"`
	EntityType     string      `json:"entity_type"`
	EntityID       pgtype.UUID `json:"entity_id"`
	ChangeType     string      `json:"change_type"`
	Metadata       []byte      `json:"metadata"`
}

type CanonVersion struct {
	ID                         pgtype.UUID        `json:"id"`
	StoryID                    pgtype.UUID        `json:"story_id"`
	BranchID                   pgtype.UUID        `json:"branch_id"`
	SequenceNo                 int32              `json:"sequence_no"`
	ParentVersionID            pgtype.UUID        `json:"parent_version_id"`
	SourceChapterID            pgtype.UUID        `json:"source_chapter_id"`
	SourceContentRevisionID    pgtype.UUID        `json:"source_content_revision_id"`
	SourceProvisionalVersionID pgtype.UUID        `json:"source_provisional_version_id"`
	GenerationRunID            pgtype.UUID        `json:"generation_run_id"`
	RetconRequestID            pgtype.UUID        `json:"retcon_request_id"`
	Status                     string             `json:"status"`
	CommittedBy                pgtype.UUID        `json:"committed_by"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
}

type Chapter struct {
	ID                         pgtype.UUID        `json:"id"`
	StoryID                    pgtype.UUID        `json:"story_id"`
	ChapterNumber              int32              `json:"chapter_number"`
	Title                      pgtype.Text        `json:"title"`
	Status                     string             `json:"status"`
	ArcID                      pgtype.UUID        `json:"arc_id"`
	CurrentPlanRevisionID      pgtype.UUID        `json:"current_plan_revision_id"`
	CurrentContentRevisionID   pgtype.UUID        `json:"current_content_revision_id"`
	CurrentNarrationRevisionID pgtype.UUID        `json:"current_narration_revision_id"`
	CurrentAudioAssetID        pgtype.UUID        `json:"current_audio_asset_id"`
	OfficialCanonVersionID     pgtype.UUID        `json:"official_canon_version_id"`
	PublishedAt                pgtype.Timestamptz `json:"published_at"`
	ArchivedAt                 pgtype.Timestamptz `json:"archived_at"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type ChapterContentRevision struct {
	ID                 pgtype.UUID        `json:"id"`
	ChapterID          pgtype.UUID        `json:"chapter_id"`
	RevisionNo         int32              `json:"revision_no"`
	ContentText        string             `json:"content_text"`
	SourceType         string             `json:"source_type"`
	BasedOnRevisionID  pgtype.UUID        `json:"based_on_revision_id"`
	PlanRevisionID     pgtype.UUID        `json:"plan_revision_id"`
	BaseCanonVersionID pgtype.UUID        `json:"base_canon_version_id"`
	GenerationRunID    pgtype.UUID        `json:"generation_run_id"`
	RetconRequestID    pgtype.UUID        `json:"retcon_request_id"`
	Status             string             `json:"status"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ChapterPlanRevision struct {
	ID                 pgtype.UUID        `json:"id"`
	ChapterID          pgtype.UUID        `json:"chapter_id"`
	RevisionNo         int32              `json:"revision_no"`
	Plan               []byte             `json:"plan"`
	BaseCanonVersionID pgtype.UUID        `json:"base_canon_version_id"`
	ArcVersionID       pgtype.UUID        `json:"arc_version_id"`
	SourceType         string             `json:"source_type"`
	GenerationRunID    pgtype.UUID        `json:"generation_run_id"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ChapterReview struct {
	ID                pgtype.UUID        `json:"id"`
	ChapterID         pgtype.UUID        `json:"chapter_id"`
	ContentRevisionID pgtype.UUID        `json:"content_revision_id"`
	ReviewType        string             `json:"review_type"`
	CanonVersionID    pgtype.UUID        `json:"canon_version_id"`
	PolicyVersionID   pgtype.UUID        `json:"policy_version_id"`
	Outcome           string             `json:"outcome"`
	Report            []byte             `json:"report"`
	GenerationRunID   pgtype.UUID        `json:"generation_run_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ChapterSummary struct {
	ID                pgtype.UUID        `json:"id"`
	ChapterID         pgtype.UUID        `json:"chapter_id"`
	ContentRevisionID pgtype.UUID        `json:"content_revision_id"`
	Summary           string             `json:"summary"`
	GenerationRunID   pgtype.UUID        `json:"generation_run_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Character struct {
	ID                      pgtype.UUID        `json:"id"`
	StoryID                 pgtype.UUID        `json:"story_id"`
	CanonicalName           string             `json:"canonical_name"`
	Importance              string             `json:"importance"`
	CurrentProfileVersionID pgtype.UUID        `json:"current_profile_version_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type CharacterProfileVersion struct {
	ID                 pgtype.UUID        `json:"id"`
	CharacterID        pgtype.UUID        `json:"character_id"`
	VersionNo          int32              `json:"version_no"`
	Profile            []byte             `json:"profile"`
	BaseCanonVersionID pgtype.UUID        `json:"base_canon_version_id"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	GenerationRunID    pgtype.UUID        `json:"generation_run_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type CharacterStateVersion struct {
	ID                      pgtype.UUID        `json:"id"`
	CharacterID             pgtype.UUID        `json:"character_id"`
	CanonVersionID          pgtype.UUID        `json:"canon_version_id"`
	State                   []byte             `json:"state"`
	SourceChapterID         pgtype.UUID        `json:"source_chapter_id"`
	SourceContentRevisionID pgtype.UUID        `json:"source_content_revision_id"`
	GenerationRunID         pgtype.UUID        `json:"generation_run_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type ContentApproval struct {
	ID                pgtype.UUID        `json:"id"`
	ChapterID         pgtype.UUID        `json:"chapter_id"`
	ContentRevisionID pgtype.UUID        `json:"content_revision_id"`
	ApprovedBy        pgtype.UUID        `json:"approved_by"`
	ApprovedAt        pgtype.Timestamptz `json:"approved_at"`
	WarningsSnapshot  []byte             `json:"warnings_snapshot"`
	OverrideSnapshot  []byte             `json:"override_snapshot"`
}

type ContentClassification struct {
	ID                pgtype.UUID        `json:"id"`
	ContentRevisionID pgtype.UUID        `json:"content_revision_id"`
	Rating            pgtype.Text        `json:"rating"`
	Warnings          []string           `json:"warnings"`
	Outcome           string             `json:"outcome"`
	PolicyVersionID   pgtype.UUID        `json:"policy_version_id"`
	Report            []byte             `json:"report"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ContextSnapshot struct {
	ID                      pgtype.UUID        `json:"id"`
	RunID                   pgtype.UUID        `json:"run_id"`
	StoryID                 pgtype.UUID        `json:"story_id"`
	ChapterID               pgtype.UUID        `json:"chapter_id"`
	CanonVersionID          pgtype.UUID        `json:"canon_version_id"`
	BibleVersionID          pgtype.UUID        `json:"bible_version_id"`
	EndingPlanVersionID     pgtype.UUID        `json:"ending_plan_version_id"`
	ArcVersionID            pgtype.UUID        `json:"arc_version_id"`
	ContentProfileVersionID pgtype.UUID        `json:"content_profile_version_id"`
	PromptVersion           pgtype.Text        `json:"prompt_version"`
	WorkflowVersion         pgtype.Text        `json:"workflow_version"`
	Provider                pgtype.Text        `json:"provider"`
	Model                   pgtype.Text        `json:"model"`
	IncludedRefs            []byte             `json:"included_refs"`
	HistoricalHits          []byte             `json:"historical_hits"`
	AdminInstruction        pgtype.Text        `json:"admin_instruction"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type EmailVerificationToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GenerationJob struct {
	ID               pgtype.UUID        `json:"id"`
	RunID            pgtype.UUID        `json:"run_id"`
	JobType          string             `json:"job_type"`
	Status           string             `json:"status"`
	Priority         int32              `json:"priority"`
	AvailableAt      pgtype.Timestamptz `json:"available_at"`
	InputFingerprint pgtype.Text        `json:"input_fingerprint"`
	AttemptCount     int32              `json:"attempt_count"`
	MaxAttempts      int32              `json:"max_attempts"`
	LockedBy         pgtype.Text        `json:"locked_by"`
	LockExpiresAt    pgtype.Timestamptz `json:"lock_expires_at"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	LastErrorClass   pgtype.Text        `json:"last_error_class"`
	LastErrorCode    pgtype.Text        `json:"last_error_code"`
	OutputRef        []byte             `json:"output_ref"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type GenerationJobAttempt struct {
	ID              pgtype.UUID        `json:"id"`
	JobID           pgtype.UUID        `json:"job_id"`
	AttemptNo       int32              `json:"attempt_no"`
	Provider        pgtype.Text        `json:"provider"`
	Model           pgtype.Text        `json:"model"`
	Status          string             `json:"status"`
	ErrorClass      pgtype.Text        `json:"error_class"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	SafeErrorDetail []byte             `json:"safe_error_detail"`
	Usage           []byte             `json:"usage"`
	LatencyMs       pgtype.Int4        `json:"latency_ms"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type GenerationJobDependency struct {
	JobID          pgtype.UUID `json:"job_id"`
	DependsOnJobID pgtype.UUID `json:"depends_on_job_id"`
}

type GenerationRun struct {
	ID                 pgtype.UUID        `json:"id"`
	RunType            string             `json:"run_type"`
	StoryID            pgtype.UUID        `json:"story_id"`
	ChapterID          pgtype.UUID        `json:"chapter_id"`
	Status             string             `json:"status"`
	WaitingReason      pgtype.Text        `json:"waiting_reason"`
	WorkflowVersion    pgtype.Text        `json:"workflow_version"`
	Priority           int32              `json:"priority"`
	BaseCanonVersionID pgtype.UUID        `json:"base_canon_version_id"`
	ContextSnapshotID  pgtype.UUID        `json:"context_snapshot_id"`
	RequestedBy        pgtype.UUID        `json:"requested_by"`
	IdempotencyKey     pgtype.Text        `json:"idempotency_key"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Genre struct {
	ID   pgtype.UUID `json:"id"`
	Slug string      `json:"slug"`
	Name string      `json:"name"`
}

type PasswordResetToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	ID   pgtype.UUID `json:"id"`
	Code string      `json:"code"`
}

type PlotThread struct {
	ID                    pgtype.UUID        `json:"id"`
	StoryID               pgtype.UUID        `json:"story_id"`
	Title                 string             `json:"title"`
	Summary               pgtype.Text        `json:"summary"`
	Importance            string             `json:"importance"`
	Status                string             `json:"status"`
	OpenedChapterID       pgtype.UUID        `json:"opened_chapter_id"`
	ResolvedChapterID     pgtype.UUID        `json:"resolved_chapter_id"`
	LastAdvancedChapterID pgtype.UUID        `json:"last_advanced_chapter_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type PlotThreadEvent struct {
	ID             pgtype.UUID        `json:"id"`
	PlotThreadID   pgtype.UUID        `json:"plot_thread_id"`
	CanonVersionID pgtype.UUID        `json:"canon_version_id"`
	ChapterID      pgtype.UUID        `json:"chapter_id"`
	EventType      string             `json:"event_type"`
	Detail         []byte             `json:"detail"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID   pgtype.UUID `json:"id"`
	Code string      `json:"code"`
}

type RolePermission struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

type SchemaBootstrap struct {
	ID        bool               `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Story struct {
	ID                             pgtype.UUID        `json:"id"`
	Slug                           string             `json:"slug"`
	Title                          string             `json:"title"`
	Description                    pgtype.Text        `json:"description"`
	Status                         string             `json:"status"`
	Visibility                     string             `json:"visibility"`
	PlanningMode                   string             `json:"planning_mode"`
	PlanningPhase                  string             `json:"planning_phase"`
	PublicRating                   pgtype.Text        `json:"public_rating"`
	PublicWarnings                 []string           `json:"public_warnings"`
	CoverAssetID                   pgtype.UUID        `json:"cover_asset_id"`
	CurrentStoryBibleVersionID     pgtype.UUID        `json:"current_story_bible_version_id"`
	CurrentEndingPlanVersionID     pgtype.UUID        `json:"current_ending_plan_version_id"`
	CurrentContentProfileVersionID pgtype.UUID        `json:"current_content_profile_version_id"`
	CurrentOfficialCanonVersionID  pgtype.UUID        `json:"current_official_canon_version_id"`
	PublicSince                    pgtype.Timestamptz `json:"public_since"`
	LastPublishedAt                pgtype.Timestamptz `json:"last_published_at"`
	StatusBeforeArchive            pgtype.Text        `json:"status_before_archive"`
	CreatedBy                      pgtype.UUID        `json:"created_by"`
	CreatedAt                      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                      pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt                     pgtype.Timestamptz `json:"archived_at"`
}

type StoryArc struct {
	ID               pgtype.UUID        `json:"id"`
	StoryID          pgtype.UUID        `json:"story_id"`
	Ordinal          int32              `json:"ordinal"`
	Status           string             `json:"status"`
	CurrentVersionID pgtype.UUID        `json:"current_version_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type StoryArcVersion struct {
	ID                 pgtype.UUID        `json:"id"`
	ArcID              pgtype.UUID        `json:"arc_id"`
	VersionNo          int32              `json:"version_no"`
	Content            []byte             `json:"content"`
	BaseCanonVersionID pgtype.UUID        `json:"base_canon_version_id"`
	GenerationRunID    pgtype.UUID        `json:"generation_run_id"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type StoryAsset struct {
	ID           pgtype.UUID        `json:"id"`
	StoryID      pgtype.UUID        `json:"story_id"`
	Type         string             `json:"type"`
	StorageKey   string             `json:"storage_key"`
	MimeType     pgtype.Text        `json:"mime_type"`
	SizeBytes    pgtype.Int8        `json:"size_bytes"`
	Checksum     pgtype.Text        `json:"checksum"`
	RightsStatus pgtype.Text        `json:"rights_status"`
	Status       string             `json:"status"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type StoryBibleVersion struct {
	ID               pgtype.UUID        `json:"id"`
	StoryID          pgtype.UUID        `json:"story_id"`
	VersionNo        int32              `json:"version_no"`
	Content          []byte             `json:"content"`
	BasedOnVersionID pgtype.UUID        `json:"based_on_version_id"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	GenerationRunID  pgtype.UUID        `json:"generation_run_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type StoryContentProfileVersion struct {
	ID                  pgtype.UUID        `json:"id"`
	StoryID             pgtype.UUID        `json:"story_id"`
	VersionNo           int32              `json:"version_no"`
	Profile             []byte             `json:"profile"`
	BasePolicyVersionID pgtype.UUID        `json:"base_policy_version_id"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type StoryEndingPlanVersion struct {
	ID               pgtype.UUID        `json:"id"`
	StoryID          pgtype.UUID        `json:"story_id"`
	VersionNo        int32              `json:"version_no"`
	Content          []byte             `json:"content"`
	BasedOnVersionID pgtype.UUID        `json:"based_on_version_id"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	GenerationRunID  pgtype.UUID        `json:"generation_run_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type StoryFact struct {
	ID                          pgtype.UUID        `json:"id"`
	StoryID                     pgtype.UUID        `json:"story_id"`
	SubjectType                 pgtype.Text        `json:"subject_type"`
	SubjectID                   pgtype.UUID        `json:"subject_id"`
	FactType                    string             `json:"fact_type"`
	Value                       []byte             `json:"value"`
	Importance                  string             `json:"importance"`
	Status                      string             `json:"status"`
	ValidFromCanonVersionID     pgtype.UUID        `json:"valid_from_canon_version_id"`
	InvalidatedAtCanonVersionID pgtype.UUID        `json:"invalidated_at_canon_version_id"`
	SupersedesFactID            pgtype.UUID        `json:"supersedes_fact_id"`
	SourceChapterID             pgtype.UUID        `json:"source_chapter_id"`
	SourceContentRevisionID     pgtype.UUID        `json:"source_content_revision_id"`
	GenerationRunID             pgtype.UUID        `json:"generation_run_id"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
}

type StoryGenerationPolicy struct {
	StoryID                 pgtype.UUID        `json:"story_id"`
	MinimumAudioDurationSec int32              `json:"minimum_audio_duration_sec"`
	TargetAudioDurationSec  int32              `json:"target_audio_duration_sec"`
	ContentOrigin           string             `json:"content_origin"`
	Language                string             `json:"language"`
	NarrationLanguage       string             `json:"narration_language"`
	PolicyVersion           int32              `json:"policy_version"`
	CreatedBy               pgtype.UUID        `json:"created_by"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type StoryGenre struct {
	StoryID pgtype.UUID `json:"story_id"`
	GenreID pgtype.UUID `json:"genre_id"`
}

type StorySummary struct {
	ID             pgtype.UUID        `json:"id"`
	StoryID        pgtype.UUID        `json:"story_id"`
	ScopeType      string             `json:"scope_type"`
	ScopeID        pgtype.UUID        `json:"scope_id"`
	CanonVersionID pgtype.UUID        `json:"canon_version_id"`
	Summary        string             `json:"summary"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type StoryWorkflowSetting struct {
	StoryID               pgtype.UUID        `json:"story_id"`
	BatchGenerationSize   pgtype.Int4        `json:"batch_generation_size"`
	CreativeAutonomy      pgtype.Text        `json:"creative_autonomy"`
	PreferredTextProvider pgtype.Text        `json:"preferred_text_provider"`
	PreferredTextModel    pgtype.Text        `json:"preferred_text_model"`
	PreferredTtsProvider  pgtype.Text        `json:"preferred_tts_provider"`
	PreferredVoiceID      pgtype.Text        `json:"preferred_voice_id"`
	PauseBeforeTts        bool               `json:"pause_before_tts"`
	AutoAiReview          bool               `json:"auto_ai_review"`
	PlanningHorizon       pgtype.Int4        `json:"planning_horizon"`
	FallbackPolicy        []byte             `json:"fallback_policy"`
	UpdatedBy             pgtype.UUID        `json:"updated_by"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    pgtype.Text        `json:"password_hash"`
	DisplayName     pgtype.Text        `json:"display_name"`
	Status          string             `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeactivatedAt   pgtype.Timestamptz `json:"deactivated_at"`
}

type UserMfaMethod struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Type            string             `json:"type"`
	EncryptedSecret string             `json:"encrypted_secret"`
	ConfirmedAt     pgtype.Timestamptz `json:"confirmed_at"`
	DisabledAt      pgtype.Timestamptz `json:"disabled_at"`
}

type UserMfaRecoveryCode struct {
	ID       pgtype.UUID        `json:"id"`
	UserID   pgtype.UUID        `json:"user_id"`
	CodeHash string             `json:"code_hash"`
	UsedAt   pgtype.Timestamptz `json:"used_at"`
}

type UserRole struct {
	UserID    pgtype.UUID        `json:"user_id"`
	RoleID    pgtype.UUID        `json:"role_id"`
	GrantedBy pgtype.UUID        `json:"granted_by"`
	GrantedAt pgtype.Timestamptz `json:"granted_at"`
}

type UserSession struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	MfaVerifiedAt    pgtype.Timestamptz `json:"mfa_verified_at"`
	RecentAuthAt     pgtype.Timestamptz `json:"recent_auth_at"`
	UserAgentSummary pgtype.Text        `json:"user_agent_summary"`
	SafeIpMetadata   pgtype.Text        `json:"safe_ip_metadata"`
}
