// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: planning.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArc = `-- name: CreateArc :one
INSERT INTO story_arcs (id, story_id, ordinal, status)
VALUES ($1, $2, $3, $4)
RETURNING id, story_id, ordinal, status, current_version_id, created_at
`

type CreateArcParams struct {
	ID      pgtype.UUID `json:"id"`
	StoryID pgtype.UUID `json:"story_id"`
	Ordinal int32       `json:"ordinal"`
	Status  string      `json:"status"`
}

func (q *Queries) CreateArc(ctx context.Context, arg CreateArcParams) (StoryArc, error) {
	row := q.db.QueryRow(ctx, createArc,
		arg.ID,
		arg.StoryID,
		arg.Ordinal,
		arg.Status,
	)
	var i StoryArc
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.Ordinal,
		&i.Status,
		&i.CurrentVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const createArcVersion = `-- name: CreateArcVersion :one
INSERT INTO story_arc_versions (id, arc_id, version_no, content, base_canon_version_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, arc_id, version_no, content, base_canon_version_id, generation_run_id, created_by, created_at
`

type CreateArcVersionParams struct {
	ID                 pgtype.UUID `json:"id"`
	ArcID              pgtype.UUID `json:"arc_id"`
	VersionNo          int32       `json:"version_no"`
	Content            []byte      `json:"content"`
	BaseCanonVersionID pgtype.UUID `json:"base_canon_version_id"`
	CreatedBy          pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateArcVersion(ctx context.Context, arg CreateArcVersionParams) (StoryArcVersion, error) {
	row := q.db.QueryRow(ctx, createArcVersion,
		arg.ID,
		arg.ArcID,
		arg.VersionNo,
		arg.Content,
		arg.BaseCanonVersionID,
		arg.CreatedBy,
	)
	var i StoryArcVersion
	err := row.Scan(
		&i.ID,
		&i.ArcID,
		&i.VersionNo,
		&i.Content,
		&i.BaseCanonVersionID,
		&i.GenerationRunID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createAttentionItem = `-- name: CreateAttentionItem :one

INSERT INTO attention_items (id, story_id, chapter_id, priority, kind, title, detail, action)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, story_id, chapter_id, priority, kind, title, detail, action, resolved, created_at, resolved_at
`

type CreateAttentionItemParams struct {
	ID        pgtype.UUID `json:"id"`
	StoryID   pgtype.UUID `json:"story_id"`
	ChapterID pgtype.UUID `json:"chapter_id"`
	Priority  string      `json:"priority"`
	Kind      string      `json:"kind"`
	Title     string      `json:"title"`
	Detail    pgtype.Text `json:"detail"`
	Action    pgtype.Text `json:"action"`
}

// ============================================================
// Attention Items
// ============================================================
func (q *Queries) CreateAttentionItem(ctx context.Context, arg CreateAttentionItemParams) (AttentionItem, error) {
	row := q.db.QueryRow(ctx, createAttentionItem,
		arg.ID,
		arg.StoryID,
		arg.ChapterID,
		arg.Priority,
		arg.Kind,
		arg.Title,
		arg.Detail,
		arg.Action,
	)
	var i AttentionItem
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.ChapterID,
		&i.Priority,
		&i.Kind,
		&i.Title,
		&i.Detail,
		&i.Action,
		&i.Resolved,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const createBibleVersion = `-- name: CreateBibleVersion :one
INSERT INTO story_bible_versions (id, story_id, version_no, content, based_on_version_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, story_id, version_no, content, based_on_version_id, created_by, generation_run_id, created_at
`

type CreateBibleVersionParams struct {
	ID               pgtype.UUID `json:"id"`
	StoryID          pgtype.UUID `json:"story_id"`
	VersionNo        int32       `json:"version_no"`
	Content          []byte      `json:"content"`
	BasedOnVersionID pgtype.UUID `json:"based_on_version_id"`
	CreatedBy        pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateBibleVersion(ctx context.Context, arg CreateBibleVersionParams) (StoryBibleVersion, error) {
	row := q.db.QueryRow(ctx, createBibleVersion,
		arg.ID,
		arg.StoryID,
		arg.VersionNo,
		arg.Content,
		arg.BasedOnVersionID,
		arg.CreatedBy,
	)
	var i StoryBibleVersion
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.VersionNo,
		&i.Content,
		&i.BasedOnVersionID,
		&i.CreatedBy,
		&i.GenerationRunID,
		&i.CreatedAt,
	)
	return i, err
}

const createCanonBranch = `-- name: CreateCanonBranch :one

INSERT INTO canon_branches (id, story_id, type, status)
VALUES ($1, $2, $3, $4)
RETURNING id, story_id, type, status, base_version_id, generation_run_id, retcon_request_id, created_at
`

type CreateCanonBranchParams struct {
	ID      pgtype.UUID `json:"id"`
	StoryID pgtype.UUID `json:"story_id"`
	Type    string      `json:"type"`
	Status  string      `json:"status"`
}

// ============================================================
// Canon branches + versions
// ============================================================
func (q *Queries) CreateCanonBranch(ctx context.Context, arg CreateCanonBranchParams) (CanonBranch, error) {
	row := q.db.QueryRow(ctx, createCanonBranch,
		arg.ID,
		arg.StoryID,
		arg.Type,
		arg.Status,
	)
	var i CanonBranch
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.Type,
		&i.Status,
		&i.BaseVersionID,
		&i.GenerationRunID,
		&i.RetconRequestID,
		&i.CreatedAt,
	)
	return i, err
}

const createCanonChangeItem = `-- name: CreateCanonChangeItem :one
INSERT INTO canon_change_items (id, canon_version_id, entity_type, entity_id, change_type, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, canon_version_id, entity_type, entity_id, change_type, metadata
`

type CreateCanonChangeItemParams struct {
	ID             pgtype.UUID `json:"id"`
	CanonVersionID pgtype.UUID `json:"canon_version_id"`
	EntityType     string      `json:"entity_type"`
	EntityID       pgtype.UUID `json:"entity_id"`
	ChangeType     string      `json:"change_type"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) CreateCanonChangeItem(ctx context.Context, arg CreateCanonChangeItemParams) (CanonChangeItem, error) {
	row := q.db.QueryRow(ctx, createCanonChangeItem,
		arg.ID,
		arg.CanonVersionID,
		arg.EntityType,
		arg.EntityID,
		arg.ChangeType,
		arg.Metadata,
	)
	var i CanonChangeItem
	err := row.Scan(
		&i.ID,
		&i.CanonVersionID,
		&i.EntityType,
		&i.EntityID,
		&i.ChangeType,
		&i.Metadata,
	)
	return i, err
}

const createCanonVersion = `-- name: CreateCanonVersion :one
INSERT INTO canon_versions (id, story_id, branch_id, sequence_no, parent_version_id, source_chapter_id, source_content_revision_id, source_provisional_version_id, status, committed_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, story_id, branch_id, sequence_no, parent_version_id, source_chapter_id,
          source_content_revision_id, source_provisional_version_id, generation_run_id,
          retcon_request_id, status, committed_by, created_at
`

type CreateCanonVersionParams struct {
	ID                         pgtype.UUID `json:"id"`
	StoryID                    pgtype.UUID `json:"story_id"`
	BranchID                   pgtype.UUID `json:"branch_id"`
	SequenceNo                 int32       `json:"sequence_no"`
	ParentVersionID            pgtype.UUID `json:"parent_version_id"`
	SourceChapterID            pgtype.UUID `json:"source_chapter_id"`
	SourceContentRevisionID    pgtype.UUID `json:"source_content_revision_id"`
	SourceProvisionalVersionID pgtype.UUID `json:"source_provisional_version_id"`
	Status                     string      `json:"status"`
	CommittedBy                pgtype.UUID `json:"committed_by"`
}

func (q *Queries) CreateCanonVersion(ctx context.Context, arg CreateCanonVersionParams) (CanonVersion, error) {
	row := q.db.QueryRow(ctx, createCanonVersion,
		arg.ID,
		arg.StoryID,
		arg.BranchID,
		arg.SequenceNo,
		arg.ParentVersionID,
		arg.SourceChapterID,
		arg.SourceContentRevisionID,
		arg.SourceProvisionalVersionID,
		arg.Status,
		arg.CommittedBy,
	)
	var i CanonVersion
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.BranchID,
		&i.SequenceNo,
		&i.ParentVersionID,
		&i.SourceChapterID,
		&i.SourceContentRevisionID,
		&i.SourceProvisionalVersionID,
		&i.GenerationRunID,
		&i.RetconRequestID,
		&i.Status,
		&i.CommittedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createChapter = `-- name: CreateChapter :one
INSERT INTO chapters (id, story_id, chapter_number, title, status, arc_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, story_id, chapter_number, title, status, arc_id, current_plan_revision_id,
          current_content_revision_id, current_narration_revision_id, current_audio_asset_id,
          official_canon_version_id, published_at, archived_at, created_at, updated_at
`

type CreateChapterParams struct {
	ID            pgtype.UUID `json:"id"`
	StoryID       pgtype.UUID `json:"story_id"`
	ChapterNumber int32       `json:"chapter_number"`
	Title         pgtype.Text `json:"title"`
	Status        string      `json:"status"`
	ArcID         pgtype.UUID `json:"arc_id"`
}

func (q *Queries) CreateChapter(ctx context.Context, arg CreateChapterParams) (Chapter, error) {
	row := q.db.QueryRow(ctx, createChapter,
		arg.ID,
		arg.StoryID,
		arg.ChapterNumber,
		arg.Title,
		arg.Status,
		arg.ArcID,
	)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.ChapterNumber,
		&i.Title,
		&i.Status,
		&i.ArcID,
		&i.CurrentPlanRevisionID,
		&i.CurrentContentRevisionID,
		&i.CurrentNarrationRevisionID,
		&i.CurrentAudioAssetID,
		&i.OfficialCanonVersionID,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCharacter = `-- name: CreateCharacter :one

INSERT INTO characters (id, story_id, canonical_name, importance)
VALUES ($1, $2, $3, $4)
RETURNING id, story_id, canonical_name, importance, current_profile_version_id, created_at
`

type CreateCharacterParams struct {
	ID            pgtype.UUID `json:"id"`
	StoryID       pgtype.UUID `json:"story_id"`
	CanonicalName string      `json:"canonical_name"`
	Importance    string      `json:"importance"`
}

// ============================================================
// Characters
// ============================================================
func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.ID,
		arg.StoryID,
		arg.CanonicalName,
		arg.Importance,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.CanonicalName,
		&i.Importance,
		&i.CurrentProfileVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const createContextSnapshot = `-- name: CreateContextSnapshot :one

INSERT INTO context_snapshots (id, story_id, chapter_id, canon_version_id, bible_version_id,
                              ending_plan_version_id, arc_version_id, content_profile_version_id,
                              prompt_version, workflow_version, provider, model)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, run_id, story_id, chapter_id, canon_version_id, bible_version_id,
          ending_plan_version_id, arc_version_id, content_profile_version_id,
          prompt_version, workflow_version, provider, model, included_refs,
          historical_hits, admin_instruction, created_at
`

type CreateContextSnapshotParams struct {
	ID                      pgtype.UUID `json:"id"`
	StoryID                 pgtype.UUID `json:"story_id"`
	ChapterID               pgtype.UUID `json:"chapter_id"`
	CanonVersionID          pgtype.UUID `json:"canon_version_id"`
	BibleVersionID          pgtype.UUID `json:"bible_version_id"`
	EndingPlanVersionID     pgtype.UUID `json:"ending_plan_version_id"`
	ArcVersionID            pgtype.UUID `json:"arc_version_id"`
	ContentProfileVersionID pgtype.UUID `json:"content_profile_version_id"`
	PromptVersion           pgtype.Text `json:"prompt_version"`
	WorkflowVersion         pgtype.Text `json:"workflow_version"`
	Provider                pgtype.Text `json:"provider"`
	Model                   pgtype.Text `json:"model"`
}

// ============================================================
// ContextSnapshots
// ============================================================
func (q *Queries) CreateContextSnapshot(ctx context.Context, arg CreateContextSnapshotParams) (ContextSnapshot, error) {
	row := q.db.QueryRow(ctx, createContextSnapshot,
		arg.ID,
		arg.StoryID,
		arg.ChapterID,
		arg.CanonVersionID,
		arg.BibleVersionID,
		arg.EndingPlanVersionID,
		arg.ArcVersionID,
		arg.ContentProfileVersionID,
		arg.PromptVersion,
		arg.WorkflowVersion,
		arg.Provider,
		arg.Model,
	)
	var i ContextSnapshot
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StoryID,
		&i.ChapterID,
		&i.CanonVersionID,
		&i.BibleVersionID,
		&i.EndingPlanVersionID,
		&i.ArcVersionID,
		&i.ContentProfileVersionID,
		&i.PromptVersion,
		&i.WorkflowVersion,
		&i.Provider,
		&i.Model,
		&i.IncludedRefs,
		&i.HistoricalHits,
		&i.AdminInstruction,
		&i.CreatedAt,
	)
	return i, err
}

const createCreativeDecision = `-- name: CreateCreativeDecision :one

INSERT INTO creative_decisions (id, story_id, chapter_id, arc_id, origin, decision_type,
                                severity, status, blocking_level, question, context_summary,
                                created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, story_id, chapter_id, arc_id, origin, decision_type, severity, status,
          blocking_level, question, context_summary, recommended_option_id, selected_option_id,
          custom_selected_text, rejection_scope, revisit_condition, triggered_by_run_id,
          created_by, selected_by, created_at, selected_at, applied_at
`

type CreateCreativeDecisionParams struct {
	ID             pgtype.UUID `json:"id"`
	StoryID        pgtype.UUID `json:"story_id"`
	ChapterID      pgtype.UUID `json:"chapter_id"`
	ArcID          pgtype.UUID `json:"arc_id"`
	Origin         string      `json:"origin"`
	DecisionType   string      `json:"decision_type"`
	Severity       string      `json:"severity"`
	Status         string      `json:"status"`
	BlockingLevel  string      `json:"blocking_level"`
	Question       string      `json:"question"`
	ContextSummary pgtype.Text `json:"context_summary"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

// ============================================================
// Creative Decisions
// ============================================================
func (q *Queries) CreateCreativeDecision(ctx context.Context, arg CreateCreativeDecisionParams) (CreativeDecision, error) {
	row := q.db.QueryRow(ctx, createCreativeDecision,
		arg.ID,
		arg.StoryID,
		arg.ChapterID,
		arg.ArcID,
		arg.Origin,
		arg.DecisionType,
		arg.Severity,
		arg.Status,
		arg.BlockingLevel,
		arg.Question,
		arg.ContextSummary,
		arg.CreatedBy,
	)
	var i CreativeDecision
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.ChapterID,
		&i.ArcID,
		&i.Origin,
		&i.DecisionType,
		&i.Severity,
		&i.Status,
		&i.BlockingLevel,
		&i.Question,
		&i.ContextSummary,
		&i.RecommendedOptionID,
		&i.SelectedOptionID,
		&i.CustomSelectedText,
		&i.RejectionScope,
		&i.RevisitCondition,
		&i.TriggeredByRunID,
		&i.CreatedBy,
		&i.SelectedBy,
		&i.CreatedAt,
		&i.SelectedAt,
		&i.AppliedAt,
	)
	return i, err
}

const createEndingVersion = `-- name: CreateEndingVersion :one
INSERT INTO story_ending_plan_versions (id, story_id, version_no, content, based_on_version_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, story_id, version_no, content, based_on_version_id, created_by, generation_run_id, created_at
`

type CreateEndingVersionParams struct {
	ID               pgtype.UUID `json:"id"`
	StoryID          pgtype.UUID `json:"story_id"`
	VersionNo        int32       `json:"version_no"`
	Content          []byte      `json:"content"`
	BasedOnVersionID pgtype.UUID `json:"based_on_version_id"`
	CreatedBy        pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateEndingVersion(ctx context.Context, arg CreateEndingVersionParams) (StoryEndingPlanVersion, error) {
	row := q.db.QueryRow(ctx, createEndingVersion,
		arg.ID,
		arg.StoryID,
		arg.VersionNo,
		arg.Content,
		arg.BasedOnVersionID,
		arg.CreatedBy,
	)
	var i StoryEndingPlanVersion
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.VersionNo,
		&i.Content,
		&i.BasedOnVersionID,
		&i.CreatedBy,
		&i.GenerationRunID,
		&i.CreatedAt,
	)
	return i, err
}

const createFact = `-- name: CreateFact :one

INSERT INTO story_facts (id, story_id, subject_type, subject_id, fact_type, value, importance, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, story_id, subject_type, subject_id, fact_type, value, importance, status,
          valid_from_canon_version_id, invalidated_at_canon_version_id, supersedes_fact_id,
          source_chapter_id, source_content_revision_id, generation_run_id, created_at
`

type CreateFactParams struct {
	ID          pgtype.UUID `json:"id"`
	StoryID     pgtype.UUID `json:"story_id"`
	SubjectType pgtype.Text `json:"subject_type"`
	SubjectID   pgtype.UUID `json:"subject_id"`
	FactType    string      `json:"fact_type"`
	Value       []byte      `json:"value"`
	Importance  string      `json:"importance"`
	Status      string      `json:"status"`
}

// ============================================================
// StoryFacts
// ============================================================
func (q *Queries) CreateFact(ctx context.Context, arg CreateFactParams) (StoryFact, error) {
	row := q.db.QueryRow(ctx, createFact,
		arg.ID,
		arg.StoryID,
		arg.SubjectType,
		arg.SubjectID,
		arg.FactType,
		arg.Value,
		arg.Importance,
		arg.Status,
	)
	var i StoryFact
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.SubjectType,
		&i.SubjectID,
		&i.FactType,
		&i.Value,
		&i.Importance,
		&i.Status,
		&i.ValidFromCanonVersionID,
		&i.InvalidatedAtCanonVersionID,
		&i.SupersedesFactID,
		&i.SourceChapterID,
		&i.SourceContentRevisionID,
		&i.GenerationRunID,
		&i.CreatedAt,
	)
	return i, err
}

const createPlanRevision = `-- name: CreatePlanRevision :one
INSERT INTO chapter_plan_revisions (id, chapter_id, revision_no, plan, base_canon_version_id, arc_version_id, source_type, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, chapter_id, revision_no, plan, base_canon_version_id, arc_version_id, source_type, generation_run_id, created_by, created_at
`

type CreatePlanRevisionParams struct {
	ID                 pgtype.UUID `json:"id"`
	ChapterID          pgtype.UUID `json:"chapter_id"`
	RevisionNo         int32       `json:"revision_no"`
	Plan               []byte      `json:"plan"`
	BaseCanonVersionID pgtype.UUID `json:"base_canon_version_id"`
	ArcVersionID       pgtype.UUID `json:"arc_version_id"`
	SourceType         string      `json:"source_type"`
	CreatedBy          pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreatePlanRevision(ctx context.Context, arg CreatePlanRevisionParams) (ChapterPlanRevision, error) {
	row := q.db.QueryRow(ctx, createPlanRevision,
		arg.ID,
		arg.ChapterID,
		arg.RevisionNo,
		arg.Plan,
		arg.BaseCanonVersionID,
		arg.ArcVersionID,
		arg.SourceType,
		arg.CreatedBy,
	)
	var i ChapterPlanRevision
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.RevisionNo,
		&i.Plan,
		&i.BaseCanonVersionID,
		&i.ArcVersionID,
		&i.SourceType,
		&i.GenerationRunID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createPlotThread = `-- name: CreatePlotThread :one

INSERT INTO plot_threads (id, story_id, title, summary, importance, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, story_id, title, summary, importance, status,
          opened_chapter_id, resolved_chapter_id, last_advanced_chapter_id, created_at, updated_at
`

type CreatePlotThreadParams struct {
	ID         pgtype.UUID `json:"id"`
	StoryID    pgtype.UUID `json:"story_id"`
	Title      string      `json:"title"`
	Summary    pgtype.Text `json:"summary"`
	Importance string      `json:"importance"`
	Status     string      `json:"status"`
}

// ============================================================
// PlotThreads
// ============================================================
func (q *Queries) CreatePlotThread(ctx context.Context, arg CreatePlotThreadParams) (PlotThread, error) {
	row := q.db.QueryRow(ctx, createPlotThread,
		arg.ID,
		arg.StoryID,
		arg.Title,
		arg.Summary,
		arg.Importance,
		arg.Status,
	)
	var i PlotThread
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.Title,
		&i.Summary,
		&i.Importance,
		&i.Status,
		&i.OpenedChapterID,
		&i.ResolvedChapterID,
		&i.LastAdvancedChapterID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlotThreadEvent = `-- name: CreatePlotThreadEvent :one
INSERT INTO plot_thread_events (id, plot_thread_id, canon_version_id, chapter_id, event_type, detail)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, plot_thread_id, canon_version_id, chapter_id, event_type, detail, created_at
`

type CreatePlotThreadEventParams struct {
	ID             pgtype.UUID `json:"id"`
	PlotThreadID   pgtype.UUID `json:"plot_thread_id"`
	CanonVersionID pgtype.UUID `json:"canon_version_id"`
	ChapterID      pgtype.UUID `json:"chapter_id"`
	EventType      string      `json:"event_type"`
	Detail         []byte      `json:"detail"`
}

func (q *Queries) CreatePlotThreadEvent(ctx context.Context, arg CreatePlotThreadEventParams) (PlotThreadEvent, error) {
	row := q.db.QueryRow(ctx, createPlotThreadEvent,
		arg.ID,
		arg.PlotThreadID,
		arg.CanonVersionID,
		arg.ChapterID,
		arg.EventType,
		arg.Detail,
	)
	var i PlotThreadEvent
	err := row.Scan(
		&i.ID,
		&i.PlotThreadID,
		&i.CanonVersionID,
		&i.ChapterID,
		&i.EventType,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const createProfileVersion = `-- name: CreateProfileVersion :one
INSERT INTO character_profile_versions (id, character_id, version_no, profile, base_canon_version_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, character_id, version_no, profile, base_canon_version_id, created_by, generation_run_id, created_at
`

type CreateProfileVersionParams struct {
	ID                 pgtype.UUID `json:"id"`
	CharacterID        pgtype.UUID `json:"character_id"`
	VersionNo          int32       `json:"version_no"`
	Profile            []byte      `json:"profile"`
	BaseCanonVersionID pgtype.UUID `json:"base_canon_version_id"`
	CreatedBy          pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateProfileVersion(ctx context.Context, arg CreateProfileVersionParams) (CharacterProfileVersion, error) {
	row := q.db.QueryRow(ctx, createProfileVersion,
		arg.ID,
		arg.CharacterID,
		arg.VersionNo,
		arg.Profile,
		arg.BaseCanonVersionID,
		arg.CreatedBy,
	)
	var i CharacterProfileVersion
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.VersionNo,
		&i.Profile,
		&i.BaseCanonVersionID,
		&i.CreatedBy,
		&i.GenerationRunID,
		&i.CreatedAt,
	)
	return i, err
}

const getArc = `-- name: GetArc :one
SELECT id, story_id, ordinal, status, current_version_id, created_at
FROM story_arcs
WHERE id = $1
`

func (q *Queries) GetArc(ctx context.Context, id pgtype.UUID) (StoryArc, error) {
	row := q.db.QueryRow(ctx, getArc, id)
	var i StoryArc
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.Ordinal,
		&i.Status,
		&i.CurrentVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const getAttentionItem = `-- name: GetAttentionItem :one
SELECT id, story_id, chapter_id, priority, kind, title, detail, action, resolved, created_at, resolved_at
FROM attention_items
WHERE id = $1
`

func (q *Queries) GetAttentionItem(ctx context.Context, id pgtype.UUID) (AttentionItem, error) {
	row := q.db.QueryRow(ctx, getAttentionItem, id)
	var i AttentionItem
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.ChapterID,
		&i.Priority,
		&i.Kind,
		&i.Title,
		&i.Detail,
		&i.Action,
		&i.Resolved,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getCanonVersion = `-- name: GetCanonVersion :one
SELECT id, story_id, branch_id, sequence_no, parent_version_id, source_chapter_id,
       source_content_revision_id, source_provisional_version_id, generation_run_id,
       retcon_request_id, status, committed_by, created_at
FROM canon_versions
WHERE id = $1
`

func (q *Queries) GetCanonVersion(ctx context.Context, id pgtype.UUID) (CanonVersion, error) {
	row := q.db.QueryRow(ctx, getCanonVersion, id)
	var i CanonVersion
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.BranchID,
		&i.SequenceNo,
		&i.ParentVersionID,
		&i.SourceChapterID,
		&i.SourceContentRevisionID,
		&i.SourceProvisionalVersionID,
		&i.GenerationRunID,
		&i.RetconRequestID,
		&i.Status,
		&i.CommittedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getChapter = `-- name: GetChapter :one
SELECT id, story_id, chapter_number, title, status, arc_id, current_plan_revision_id,
       current_content_revision_id, current_narration_revision_id, current_audio_asset_id,
       official_canon_version_id, published_at, archived_at, created_at, updated_at
FROM chapters
WHERE id = $1
`

func (q *Queries) GetChapter(ctx context.Context, id pgtype.UUID) (Chapter, error) {
	row := q.db.QueryRow(ctx, getChapter, id)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.ChapterNumber,
		&i.Title,
		&i.Status,
		&i.ArcID,
		&i.CurrentPlanRevisionID,
		&i.CurrentContentRevisionID,
		&i.CurrentNarrationRevisionID,
		&i.CurrentAudioAssetID,
		&i.OfficialCanonVersionID,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, story_id, canonical_name, importance, current_profile_version_id, created_at
FROM characters
WHERE id = $1
`

func (q *Queries) GetCharacter(ctx context.Context, id pgtype.UUID) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.CanonicalName,
		&i.Importance,
		&i.CurrentProfileVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const getContextSnapshot = `-- name: GetContextSnapshot :one
SELECT id, run_id, story_id, chapter_id, canon_version_id, bible_version_id,
       ending_plan_version_id, arc_version_id, content_profile_version_id,
       prompt_version, workflow_version, provider, model, included_refs,
       historical_hits, admin_instruction, created_at
FROM context_snapshots
WHERE id = $1
`

func (q *Queries) GetContextSnapshot(ctx context.Context, id pgtype.UUID) (ContextSnapshot, error) {
	row := q.db.QueryRow(ctx, getContextSnapshot, id)
	var i ContextSnapshot
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StoryID,
		&i.ChapterID,
		&i.CanonVersionID,
		&i.BibleVersionID,
		&i.EndingPlanVersionID,
		&i.ArcVersionID,
		&i.ContentProfileVersionID,
		&i.PromptVersion,
		&i.WorkflowVersion,
		&i.Provider,
		&i.Model,
		&i.IncludedRefs,
		&i.HistoricalHits,
		&i.AdminInstruction,
		&i.CreatedAt,
	)
	return i, err
}

const getCreativeDecision = `-- name: GetCreativeDecision :one
SELECT id, story_id, chapter_id, arc_id, origin, decision_type, severity, status,
       blocking_level, question, context_summary, recommended_option_id, selected_option_id,
       custom_selected_text, rejection_scope, revisit_condition, triggered_by_run_id,
       created_by, selected_by, created_at, selected_at, applied_at
FROM creative_decisions
WHERE id = $1
`

func (q *Queries) GetCreativeDecision(ctx context.Context, id pgtype.UUID) (CreativeDecision, error) {
	row := q.db.QueryRow(ctx, getCreativeDecision, id)
	var i CreativeDecision
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.ChapterID,
		&i.ArcID,
		&i.Origin,
		&i.DecisionType,
		&i.Severity,
		&i.Status,
		&i.BlockingLevel,
		&i.Question,
		&i.ContextSummary,
		&i.RecommendedOptionID,
		&i.SelectedOptionID,
		&i.CustomSelectedText,
		&i.RejectionScope,
		&i.RevisitCondition,
		&i.TriggeredByRunID,
		&i.CreatedBy,
		&i.SelectedBy,
		&i.CreatedAt,
		&i.SelectedAt,
		&i.AppliedAt,
	)
	return i, err
}

const getCurrentBible = `-- name: GetCurrentBible :one
SELECT id, story_id, version_no, content, based_on_version_id, created_by, generation_run_id, created_at
FROM story_bible_versions
WHERE story_id = $1
ORDER BY version_no DESC
LIMIT 1
`

func (q *Queries) GetCurrentBible(ctx context.Context, storyID pgtype.UUID) (StoryBibleVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentBible, storyID)
	var i StoryBibleVersion
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.VersionNo,
		&i.Content,
		&i.BasedOnVersionID,
		&i.CreatedBy,
		&i.GenerationRunID,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentEnding = `-- name: GetCurrentEnding :one
SELECT id, story_id, version_no, content, based_on_version_id, created_by, generation_run_id, created_at
FROM story_ending_plan_versions
WHERE story_id = $1
ORDER BY version_no DESC
LIMIT 1
`

func (q *Queries) GetCurrentEnding(ctx context.Context, storyID pgtype.UUID) (StoryEndingPlanVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentEnding, storyID)
	var i StoryEndingPlanVersion
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.VersionNo,
		&i.Content,
		&i.BasedOnVersionID,
		&i.CreatedBy,
		&i.GenerationRunID,
		&i.CreatedAt,
	)
	return i, err
}

const listArcs = `-- name: ListArcs :many
SELECT id, story_id, ordinal, status, current_version_id, created_at
FROM story_arcs
WHERE story_id = $1
ORDER BY ordinal
`

func (q *Queries) ListArcs(ctx context.Context, storyID pgtype.UUID) ([]StoryArc, error) {
	rows, err := q.db.Query(ctx, listArcs, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoryArc{}
	for rows.Next() {
		var i StoryArc
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.Ordinal,
			&i.Status,
			&i.CurrentVersionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttentionItems = `-- name: ListAttentionItems :many
SELECT id, story_id, chapter_id, priority, kind, title, detail, action, resolved, created_at, resolved_at
FROM attention_items
WHERE story_id = $1
ORDER BY created_at
`

func (q *Queries) ListAttentionItems(ctx context.Context, storyID pgtype.UUID) ([]AttentionItem, error) {
	rows, err := q.db.Query(ctx, listAttentionItems, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttentionItem{}
	for rows.Next() {
		var i AttentionItem
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.ChapterID,
			&i.Priority,
			&i.Kind,
			&i.Title,
			&i.Detail,
			&i.Action,
			&i.Resolved,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCanonChangeItems = `-- name: ListCanonChangeItems :many
SELECT id, canon_version_id, entity_type, entity_id, change_type, metadata
FROM canon_change_items
WHERE canon_version_id = $1
ORDER BY entity_type
`

func (q *Queries) ListCanonChangeItems(ctx context.Context, canonVersionID pgtype.UUID) ([]CanonChangeItem, error) {
	rows, err := q.db.Query(ctx, listCanonChangeItems, canonVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CanonChangeItem{}
	for rows.Next() {
		var i CanonChangeItem
		if err := rows.Scan(
			&i.ID,
			&i.CanonVersionID,
			&i.EntityType,
			&i.EntityID,
			&i.ChangeType,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCanonVersions = `-- name: ListCanonVersions :many
SELECT id, story_id, branch_id, sequence_no, parent_version_id, source_chapter_id,
       source_content_revision_id, source_provisional_version_id, generation_run_id,
       retcon_request_id, status, committed_by, created_at
FROM canon_versions
WHERE branch_id = $1
ORDER BY sequence_no
`

func (q *Queries) ListCanonVersions(ctx context.Context, branchID pgtype.UUID) ([]CanonVersion, error) {
	rows, err := q.db.Query(ctx, listCanonVersions, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CanonVersion{}
	for rows.Next() {
		var i CanonVersion
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.BranchID,
			&i.SequenceNo,
			&i.ParentVersionID,
			&i.SourceChapterID,
			&i.SourceContentRevisionID,
			&i.SourceProvisionalVersionID,
			&i.GenerationRunID,
			&i.RetconRequestID,
			&i.Status,
			&i.CommittedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChapters = `-- name: ListChapters :many
SELECT id, story_id, chapter_number, title, status, arc_id, current_plan_revision_id,
       current_content_revision_id, current_narration_revision_id, current_audio_asset_id,
       official_canon_version_id, published_at, archived_at, created_at, updated_at
FROM chapters
WHERE story_id = $1
ORDER BY chapter_number
`

func (q *Queries) ListChapters(ctx context.Context, storyID pgtype.UUID) ([]Chapter, error) {
	rows, err := q.db.Query(ctx, listChapters, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chapter{}
	for rows.Next() {
		var i Chapter
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.ChapterNumber,
			&i.Title,
			&i.Status,
			&i.ArcID,
			&i.CurrentPlanRevisionID,
			&i.CurrentContentRevisionID,
			&i.CurrentNarrationRevisionID,
			&i.CurrentAudioAssetID,
			&i.OfficialCanonVersionID,
			&i.PublishedAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharacters = `-- name: ListCharacters :many
SELECT id, story_id, canonical_name, importance, current_profile_version_id, created_at
FROM characters
WHERE story_id = $1
ORDER BY created_at
`

func (q *Queries) ListCharacters(ctx context.Context, storyID pgtype.UUID) ([]Character, error) {
	rows, err := q.db.Query(ctx, listCharacters, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Character{}
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.CanonicalName,
			&i.Importance,
			&i.CurrentProfileVersionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContextSnapshots = `-- name: ListContextSnapshots :many
SELECT id, run_id, story_id, chapter_id, canon_version_id, bible_version_id,
       ending_plan_version_id, arc_version_id, content_profile_version_id,
       prompt_version, workflow_version, provider, model, included_refs,
       historical_hits, admin_instruction, created_at
FROM context_snapshots
WHERE story_id = $1
ORDER BY created_at
`

func (q *Queries) ListContextSnapshots(ctx context.Context, storyID pgtype.UUID) ([]ContextSnapshot, error) {
	rows, err := q.db.Query(ctx, listContextSnapshots, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContextSnapshot{}
	for rows.Next() {
		var i ContextSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StoryID,
			&i.ChapterID,
			&i.CanonVersionID,
			&i.BibleVersionID,
			&i.EndingPlanVersionID,
			&i.ArcVersionID,
			&i.ContentProfileVersionID,
			&i.PromptVersion,
			&i.WorkflowVersion,
			&i.Provider,
			&i.Model,
			&i.IncludedRefs,
			&i.HistoricalHits,
			&i.AdminInstruction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreativeDecisions = `-- name: ListCreativeDecisions :many
SELECT id, story_id, chapter_id, arc_id, origin, decision_type, severity, status,
       blocking_level, question, context_summary, recommended_option_id, selected_option_id,
       custom_selected_text, rejection_scope, revisit_condition, triggered_by_run_id,
       created_by, selected_by, created_at, selected_at, applied_at
FROM creative_decisions
WHERE story_id = $1
ORDER BY created_at
`

func (q *Queries) ListCreativeDecisions(ctx context.Context, storyID pgtype.UUID) ([]CreativeDecision, error) {
	rows, err := q.db.Query(ctx, listCreativeDecisions, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CreativeDecision{}
	for rows.Next() {
		var i CreativeDecision
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.ChapterID,
			&i.ArcID,
			&i.Origin,
			&i.DecisionType,
			&i.Severity,
			&i.Status,
			&i.BlockingLevel,
			&i.Question,
			&i.ContextSummary,
			&i.RecommendedOptionID,
			&i.SelectedOptionID,
			&i.CustomSelectedText,
			&i.RejectionScope,
			&i.RevisitCondition,
			&i.TriggeredByRunID,
			&i.CreatedBy,
			&i.SelectedBy,
			&i.CreatedAt,
			&i.SelectedAt,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFacts = `-- name: ListFacts :many
SELECT id, story_id, subject_type, subject_id, fact_type, value, importance, status,
       valid_from_canon_version_id, invalidated_at_canon_version_id, supersedes_fact_id,
       source_chapter_id, source_content_revision_id, generation_run_id, created_at
FROM story_facts
WHERE story_id = $1
ORDER BY created_at
`

func (q *Queries) ListFacts(ctx context.Context, storyID pgtype.UUID) ([]StoryFact, error) {
	rows, err := q.db.Query(ctx, listFacts, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoryFact{}
	for rows.Next() {
		var i StoryFact
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.SubjectType,
			&i.SubjectID,
			&i.FactType,
			&i.Value,
			&i.Importance,
			&i.Status,
			&i.ValidFromCanonVersionID,
			&i.InvalidatedAtCanonVersionID,
			&i.SupersedesFactID,
			&i.SourceChapterID,
			&i.SourceContentRevisionID,
			&i.GenerationRunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlotThreadEvents = `-- name: ListPlotThreadEvents :many
SELECT id, plot_thread_id, canon_version_id, chapter_id, event_type, detail, created_at
FROM plot_thread_events
WHERE plot_thread_id = $1
ORDER BY created_at
`

func (q *Queries) ListPlotThreadEvents(ctx context.Context, plotThreadID pgtype.UUID) ([]PlotThreadEvent, error) {
	rows, err := q.db.Query(ctx, listPlotThreadEvents, plotThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlotThreadEvent{}
	for rows.Next() {
		var i PlotThreadEvent
		if err := rows.Scan(
			&i.ID,
			&i.PlotThreadID,
			&i.CanonVersionID,
			&i.ChapterID,
			&i.EventType,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlotThreads = `-- name: ListPlotThreads :many
SELECT id, story_id, title, summary, importance, status,
       opened_chapter_id, resolved_chapter_id, last_advanced_chapter_id, created_at, updated_at
FROM plot_threads
WHERE story_id = $1
ORDER BY created_at
`

func (q *Queries) ListPlotThreads(ctx context.Context, storyID pgtype.UUID) ([]PlotThread, error) {
	rows, err := q.db.Query(ctx, listPlotThreads, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlotThread{}
	for rows.Next() {
		var i PlotThread
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.Title,
			&i.Summary,
			&i.Importance,
			&i.Status,
			&i.OpenedChapterID,
			&i.ResolvedChapterID,
			&i.LastAdvancedChapterID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextArcOrdinal = `-- name: NextArcOrdinal :one

SELECT COALESCE(MAX(ordinal), 0) + 1
FROM story_arcs
WHERE story_id = $1
`

// ============================================================
// Story Arcs
// ============================================================
func (q *Queries) NextArcOrdinal(ctx context.Context, storyID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextArcOrdinal, storyID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextArcVersion = `-- name: NextArcVersion :one
SELECT COALESCE(MAX(version_no), 0) + 1
FROM story_arc_versions
WHERE arc_id = $1
`

func (q *Queries) NextArcVersion(ctx context.Context, arcID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextArcVersion, arcID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextBibleVersion = `-- name: NextBibleVersion :one

SELECT COALESCE(MAX(version_no), 0) + 1
FROM story_bible_versions
WHERE story_id = $1
`

// ============================================================
// Story Bible
// ============================================================
func (q *Queries) NextBibleVersion(ctx context.Context, storyID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextBibleVersion, storyID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextCanonSequence = `-- name: NextCanonSequence :one
SELECT COALESCE(MAX(sequence_no), 0) + 1
FROM canon_versions
WHERE branch_id = $1
`

func (q *Queries) NextCanonSequence(ctx context.Context, branchID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextCanonSequence, branchID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextChapterNumber = `-- name: NextChapterNumber :one

SELECT COALESCE(MAX(chapter_number), 0) + 1
FROM chapters
WHERE story_id = $1
`

// ============================================================
// Chapters
// ============================================================
func (q *Queries) NextChapterNumber(ctx context.Context, storyID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextChapterNumber, storyID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextEndingVersion = `-- name: NextEndingVersion :one

SELECT COALESCE(MAX(version_no), 0) + 1
FROM story_ending_plan_versions
WHERE story_id = $1
`

// ============================================================
// Ending Plan
// ============================================================
func (q *Queries) NextEndingVersion(ctx context.Context, storyID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextEndingVersion, storyID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextPlanRevision = `-- name: NextPlanRevision :one
SELECT COALESCE(MAX(revision_no), 0) + 1
FROM chapter_plan_revisions
WHERE chapter_id = $1
`

func (q *Queries) NextPlanRevision(ctx context.Context, chapterID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextPlanRevision, chapterID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextProfileVersion = `-- name: NextProfileVersion :one
SELECT COALESCE(MAX(version_no), 0) + 1
FROM character_profile_versions
WHERE character_id = $1
`

func (q *Queries) NextProfileVersion(ctx context.Context, characterID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextProfileVersion, characterID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const updateAttentionItem = `-- name: UpdateAttentionItem :one
UPDATE attention_items
SET resolved = $2,
    resolved_at = CASE WHEN $2 = TRUE THEN NOW() ELSE resolved_at END
WHERE id = $1
RETURNING id, story_id, chapter_id, priority, kind, title, detail, action, resolved, created_at, resolved_at
`

type UpdateAttentionItemParams struct {
	ID       pgtype.UUID `json:"id"`
	Resolved bool        `json:"resolved"`
}

func (q *Queries) UpdateAttentionItem(ctx context.Context, arg UpdateAttentionItemParams) (AttentionItem, error) {
	row := q.db.QueryRow(ctx, updateAttentionItem, arg.ID, arg.Resolved)
	var i AttentionItem
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.ChapterID,
		&i.Priority,
		&i.Kind,
		&i.Title,
		&i.Detail,
		&i.Action,
		&i.Resolved,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const updateCanonVersion = `-- name: UpdateCanonVersion :one
UPDATE canon_versions
SET status = $2,
    committed_by = $3
WHERE id = $1
RETURNING id, story_id, branch_id, sequence_no, parent_version_id, source_chapter_id,
          source_content_revision_id, source_provisional_version_id, generation_run_id,
          retcon_request_id, status, committed_by, created_at
`

type UpdateCanonVersionParams struct {
	ID          pgtype.UUID `json:"id"`
	Status      string      `json:"status"`
	CommittedBy pgtype.UUID `json:"committed_by"`
}

func (q *Queries) UpdateCanonVersion(ctx context.Context, arg UpdateCanonVersionParams) (CanonVersion, error) {
	row := q.db.QueryRow(ctx, updateCanonVersion, arg.ID, arg.Status, arg.CommittedBy)
	var i CanonVersion
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.BranchID,
		&i.SequenceNo,
		&i.ParentVersionID,
		&i.SourceChapterID,
		&i.SourceContentRevisionID,
		&i.SourceProvisionalVersionID,
		&i.GenerationRunID,
		&i.RetconRequestID,
		&i.Status,
		&i.CommittedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateChapterStatus = `-- name: UpdateChapterStatus :one
UPDATE chapters
SET status = $2,
    published_at = CASE WHEN $2 = 'PUBLISHED' THEN NOW() ELSE published_at END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, story_id, chapter_number, title, status, arc_id, current_plan_revision_id,
          current_content_revision_id, current_narration_revision_id, current_audio_asset_id,
          official_canon_version_id, published_at, archived_at, created_at, updated_at
`

type UpdateChapterStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateChapterStatus(ctx context.Context, arg UpdateChapterStatusParams) (Chapter, error) {
	row := q.db.QueryRow(ctx, updateChapterStatus, arg.ID, arg.Status)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.ChapterNumber,
		&i.Title,
		&i.Status,
		&i.ArcID,
		&i.CurrentPlanRevisionID,
		&i.CurrentContentRevisionID,
		&i.CurrentNarrationRevisionID,
		&i.CurrentAudioAssetID,
		&i.OfficialCanonVersionID,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCreativeDecision = `-- name: UpdateCreativeDecision :one
UPDATE creative_decisions
SET status = $2,
    selected_option_id = $3,
    custom_selected_text = $4,
    rejection_scope = $5,
    selected_by = $6,
    selected_at = CASE WHEN $2 = 'SELECTED' THEN NOW() ELSE selected_at END,
    applied_at = CASE WHEN $2 = 'APPLIED' THEN NOW() ELSE applied_at END
WHERE id = $1
RETURNING id, story_id, chapter_id, arc_id, origin, decision_type, severity, status,
          blocking_level, question, context_summary, recommended_option_id, selected_option_id,
          custom_selected_text, rejection_scope, revisit_condition, triggered_by_run_id,
          created_by, selected_by, created_at, selected_at, applied_at
`

type UpdateCreativeDecisionParams struct {
	ID                 pgtype.UUID `json:"id"`
	Status             string      `json:"status"`
	SelectedOptionID   pgtype.UUID `json:"selected_option_id"`
	CustomSelectedText pgtype.Text `json:"custom_selected_text"`
	RejectionScope     pgtype.Text `json:"rejection_scope"`
	SelectedBy         pgtype.UUID `json:"selected_by"`
}

func (q *Queries) UpdateCreativeDecision(ctx context.Context, arg UpdateCreativeDecisionParams) (CreativeDecision, error) {
	row := q.db.QueryRow(ctx, updateCreativeDecision,
		arg.ID,
		arg.Status,
		arg.SelectedOptionID,
		arg.CustomSelectedText,
		arg.RejectionScope,
		arg.SelectedBy,
	)
	var i CreativeDecision
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.ChapterID,
		&i.ArcID,
		&i.Origin,
		&i.DecisionType,
		&i.Severity,
		&i.Status,
		&i.BlockingLevel,
		&i.Question,
		&i.ContextSummary,
		&i.RecommendedOptionID,
		&i.SelectedOptionID,
		&i.CustomSelectedText,
		&i.RejectionScope,
		&i.RevisitCondition,
		&i.TriggeredByRunID,
		&i.CreatedBy,
		&i.SelectedBy,
		&i.CreatedAt,
		&i.SelectedAt,
		&i.AppliedAt,
	)
	return i, err
}
