// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: planning.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArc = `-- name: CreateArc :one
INSERT INTO story_arcs (id, story_id, ordinal, status)
VALUES ($1, $2, $3, $4)
RETURNING id, story_id, ordinal, status, current_version_id, created_at
`

type CreateArcParams struct {
	ID      pgtype.UUID `json:"id"`
	StoryID pgtype.UUID `json:"story_id"`
	Ordinal int32       `json:"ordinal"`
	Status  string      `json:"status"`
}

func (q *Queries) CreateArc(ctx context.Context, arg CreateArcParams) (StoryArc, error) {
	row := q.db.QueryRow(ctx, createArc,
		arg.ID,
		arg.StoryID,
		arg.Ordinal,
		arg.Status,
	)
	var i StoryArc
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.Ordinal,
		&i.Status,
		&i.CurrentVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const createArcVersion = `-- name: CreateArcVersion :one
INSERT INTO story_arc_versions (id, arc_id, version_no, content, base_canon_version_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, arc_id, version_no, content, base_canon_version_id, generation_run_id, created_by, created_at
`

type CreateArcVersionParams struct {
	ID                 pgtype.UUID `json:"id"`
	ArcID              pgtype.UUID `json:"arc_id"`
	VersionNo          int32       `json:"version_no"`
	Content            []byte      `json:"content"`
	BaseCanonVersionID pgtype.UUID `json:"base_canon_version_id"`
	CreatedBy          pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateArcVersion(ctx context.Context, arg CreateArcVersionParams) (StoryArcVersion, error) {
	row := q.db.QueryRow(ctx, createArcVersion,
		arg.ID,
		arg.ArcID,
		arg.VersionNo,
		arg.Content,
		arg.BaseCanonVersionID,
		arg.CreatedBy,
	)
	var i StoryArcVersion
	err := row.Scan(
		&i.ID,
		&i.ArcID,
		&i.VersionNo,
		&i.Content,
		&i.BaseCanonVersionID,
		&i.GenerationRunID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createBibleVersion = `-- name: CreateBibleVersion :one
INSERT INTO story_bible_versions (id, story_id, version_no, content, based_on_version_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, story_id, version_no, content, based_on_version_id, created_by, generation_run_id, created_at
`

type CreateBibleVersionParams struct {
	ID               pgtype.UUID `json:"id"`
	StoryID          pgtype.UUID `json:"story_id"`
	VersionNo        int32       `json:"version_no"`
	Content          []byte      `json:"content"`
	BasedOnVersionID pgtype.UUID `json:"based_on_version_id"`
	CreatedBy        pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateBibleVersion(ctx context.Context, arg CreateBibleVersionParams) (StoryBibleVersion, error) {
	row := q.db.QueryRow(ctx, createBibleVersion,
		arg.ID,
		arg.StoryID,
		arg.VersionNo,
		arg.Content,
		arg.BasedOnVersionID,
		arg.CreatedBy,
	)
	var i StoryBibleVersion
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.VersionNo,
		&i.Content,
		&i.BasedOnVersionID,
		&i.CreatedBy,
		&i.GenerationRunID,
		&i.CreatedAt,
	)
	return i, err
}

const createCharacter = `-- name: CreateCharacter :one

INSERT INTO characters (id, story_id, canonical_name, importance)
VALUES ($1, $2, $3, $4)
RETURNING id, story_id, canonical_name, importance, current_profile_version_id, created_at
`

type CreateCharacterParams struct {
	ID            pgtype.UUID `json:"id"`
	StoryID       pgtype.UUID `json:"story_id"`
	CanonicalName string      `json:"canonical_name"`
	Importance    string      `json:"importance"`
}

// ============================================================
// Characters
// ============================================================
func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.ID,
		arg.StoryID,
		arg.CanonicalName,
		arg.Importance,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.CanonicalName,
		&i.Importance,
		&i.CurrentProfileVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const createEndingVersion = `-- name: CreateEndingVersion :one
INSERT INTO story_ending_plan_versions (id, story_id, version_no, content, based_on_version_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, story_id, version_no, content, based_on_version_id, created_by, generation_run_id, created_at
`

type CreateEndingVersionParams struct {
	ID               pgtype.UUID `json:"id"`
	StoryID          pgtype.UUID `json:"story_id"`
	VersionNo        int32       `json:"version_no"`
	Content          []byte      `json:"content"`
	BasedOnVersionID pgtype.UUID `json:"based_on_version_id"`
	CreatedBy        pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateEndingVersion(ctx context.Context, arg CreateEndingVersionParams) (StoryEndingPlanVersion, error) {
	row := q.db.QueryRow(ctx, createEndingVersion,
		arg.ID,
		arg.StoryID,
		arg.VersionNo,
		arg.Content,
		arg.BasedOnVersionID,
		arg.CreatedBy,
	)
	var i StoryEndingPlanVersion
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.VersionNo,
		&i.Content,
		&i.BasedOnVersionID,
		&i.CreatedBy,
		&i.GenerationRunID,
		&i.CreatedAt,
	)
	return i, err
}

const createProfileVersion = `-- name: CreateProfileVersion :one
INSERT INTO character_profile_versions (id, character_id, version_no, profile, base_canon_version_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, character_id, version_no, profile, base_canon_version_id, created_by, generation_run_id, created_at
`

type CreateProfileVersionParams struct {
	ID                 pgtype.UUID `json:"id"`
	CharacterID        pgtype.UUID `json:"character_id"`
	VersionNo          int32       `json:"version_no"`
	Profile            []byte      `json:"profile"`
	BaseCanonVersionID pgtype.UUID `json:"base_canon_version_id"`
	CreatedBy          pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateProfileVersion(ctx context.Context, arg CreateProfileVersionParams) (CharacterProfileVersion, error) {
	row := q.db.QueryRow(ctx, createProfileVersion,
		arg.ID,
		arg.CharacterID,
		arg.VersionNo,
		arg.Profile,
		arg.BaseCanonVersionID,
		arg.CreatedBy,
	)
	var i CharacterProfileVersion
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.VersionNo,
		&i.Profile,
		&i.BaseCanonVersionID,
		&i.CreatedBy,
		&i.GenerationRunID,
		&i.CreatedAt,
	)
	return i, err
}

const getArc = `-- name: GetArc :one
SELECT id, story_id, ordinal, status, current_version_id, created_at
FROM story_arcs
WHERE id = $1
`

func (q *Queries) GetArc(ctx context.Context, id pgtype.UUID) (StoryArc, error) {
	row := q.db.QueryRow(ctx, getArc, id)
	var i StoryArc
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.Ordinal,
		&i.Status,
		&i.CurrentVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, story_id, canonical_name, importance, current_profile_version_id, created_at
FROM characters
WHERE id = $1
`

func (q *Queries) GetCharacter(ctx context.Context, id pgtype.UUID) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.CanonicalName,
		&i.Importance,
		&i.CurrentProfileVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentBible = `-- name: GetCurrentBible :one
SELECT id, story_id, version_no, content, based_on_version_id, created_by, generation_run_id, created_at
FROM story_bible_versions
WHERE story_id = $1
ORDER BY version_no DESC
LIMIT 1
`

func (q *Queries) GetCurrentBible(ctx context.Context, storyID pgtype.UUID) (StoryBibleVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentBible, storyID)
	var i StoryBibleVersion
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.VersionNo,
		&i.Content,
		&i.BasedOnVersionID,
		&i.CreatedBy,
		&i.GenerationRunID,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentEnding = `-- name: GetCurrentEnding :one
SELECT id, story_id, version_no, content, based_on_version_id, created_by, generation_run_id, created_at
FROM story_ending_plan_versions
WHERE story_id = $1
ORDER BY version_no DESC
LIMIT 1
`

func (q *Queries) GetCurrentEnding(ctx context.Context, storyID pgtype.UUID) (StoryEndingPlanVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentEnding, storyID)
	var i StoryEndingPlanVersion
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.VersionNo,
		&i.Content,
		&i.BasedOnVersionID,
		&i.CreatedBy,
		&i.GenerationRunID,
		&i.CreatedAt,
	)
	return i, err
}

const listArcs = `-- name: ListArcs :many
SELECT id, story_id, ordinal, status, current_version_id, created_at
FROM story_arcs
WHERE story_id = $1
ORDER BY ordinal
`

func (q *Queries) ListArcs(ctx context.Context, storyID pgtype.UUID) ([]StoryArc, error) {
	rows, err := q.db.Query(ctx, listArcs, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoryArc{}
	for rows.Next() {
		var i StoryArc
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.Ordinal,
			&i.Status,
			&i.CurrentVersionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharacters = `-- name: ListCharacters :many
SELECT id, story_id, canonical_name, importance, current_profile_version_id, created_at
FROM characters
WHERE story_id = $1
ORDER BY created_at
`

func (q *Queries) ListCharacters(ctx context.Context, storyID pgtype.UUID) ([]Character, error) {
	rows, err := q.db.Query(ctx, listCharacters, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Character{}
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.CanonicalName,
			&i.Importance,
			&i.CurrentProfileVersionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextArcOrdinal = `-- name: NextArcOrdinal :one

SELECT COALESCE(MAX(ordinal), 0) + 1
FROM story_arcs
WHERE story_id = $1
`

// ============================================================
// Story Arcs
// ============================================================
func (q *Queries) NextArcOrdinal(ctx context.Context, storyID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextArcOrdinal, storyID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextArcVersion = `-- name: NextArcVersion :one
SELECT COALESCE(MAX(version_no), 0) + 1
FROM story_arc_versions
WHERE arc_id = $1
`

func (q *Queries) NextArcVersion(ctx context.Context, arcID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextArcVersion, arcID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextBibleVersion = `-- name: NextBibleVersion :one

SELECT COALESCE(MAX(version_no), 0) + 1
FROM story_bible_versions
WHERE story_id = $1
`

// ============================================================
// Story Bible
// ============================================================
func (q *Queries) NextBibleVersion(ctx context.Context, storyID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextBibleVersion, storyID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextEndingVersion = `-- name: NextEndingVersion :one

SELECT COALESCE(MAX(version_no), 0) + 1
FROM story_ending_plan_versions
WHERE story_id = $1
`

// ============================================================
// Ending Plan
// ============================================================
func (q *Queries) NextEndingVersion(ctx context.Context, storyID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextEndingVersion, storyID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextProfileVersion = `-- name: NextProfileVersion :one
SELECT COALESCE(MAX(version_no), 0) + 1
FROM character_profile_versions
WHERE character_id = $1
`

func (q *Queries) NextProfileVersion(ctx context.Context, characterID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextProfileVersion, characterID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
