// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: retcon.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRetconRequest = `-- name: CreateRetconRequest :one

INSERT INTO retcon_requests (id, story_id, target_chapter_id, status, impact_scope,
                             proposed_change, reason, requested_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, story_id, target_chapter_id, status, impact_scope, proposed_change, reason,
          requested_by, approved_by, applied_by, base_official_canon_version_id,
          workspace_branch_id, listener_impact, created_at, approved_at, applied_at
`

type CreateRetconRequestParams struct {
	ID              pgtype.UUID `json:"id"`
	StoryID         pgtype.UUID `json:"story_id"`
	TargetChapterID pgtype.UUID `json:"target_chapter_id"`
	Status          string      `json:"status"`
	ImpactScope     string      `json:"impact_scope"`
	ProposedChange  pgtype.Text `json:"proposed_change"`
	Reason          string      `json:"reason"`
	RequestedBy     pgtype.UUID `json:"requested_by"`
}

// ============================================================
// Retcon Requests
// ============================================================
func (q *Queries) CreateRetconRequest(ctx context.Context, arg CreateRetconRequestParams) (RetconRequest, error) {
	row := q.db.QueryRow(ctx, createRetconRequest,
		arg.ID,
		arg.StoryID,
		arg.TargetChapterID,
		arg.Status,
		arg.ImpactScope,
		arg.ProposedChange,
		arg.Reason,
		arg.RequestedBy,
	)
	var i RetconRequest
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.TargetChapterID,
		&i.Status,
		&i.ImpactScope,
		&i.ProposedChange,
		&i.Reason,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.AppliedBy,
		&i.BaseOfficialCanonVersionID,
		&i.WorkspaceBranchID,
		&i.ListenerImpact,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.AppliedAt,
	)
	return i, err
}

const getRetconRequest = `-- name: GetRetconRequest :one
SELECT id, story_id, target_chapter_id, status, impact_scope, proposed_change, reason,
       requested_by, approved_by, applied_by, base_official_canon_version_id,
       workspace_branch_id, listener_impact, created_at, approved_at, applied_at
FROM retcon_requests
WHERE id = $1
`

func (q *Queries) GetRetconRequest(ctx context.Context, id pgtype.UUID) (RetconRequest, error) {
	row := q.db.QueryRow(ctx, getRetconRequest, id)
	var i RetconRequest
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.TargetChapterID,
		&i.Status,
		&i.ImpactScope,
		&i.ProposedChange,
		&i.Reason,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.AppliedBy,
		&i.BaseOfficialCanonVersionID,
		&i.WorkspaceBranchID,
		&i.ListenerImpact,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.AppliedAt,
	)
	return i, err
}

const listRetconRequests = `-- name: ListRetconRequests :many
SELECT id, story_id, target_chapter_id, status, impact_scope, proposed_change, reason,
       requested_by, approved_by, applied_by, base_official_canon_version_id,
       workspace_branch_id, listener_impact, created_at, approved_at, applied_at
FROM retcon_requests
WHERE story_id = $1
ORDER BY created_at
`

func (q *Queries) ListRetconRequests(ctx context.Context, storyID pgtype.UUID) ([]RetconRequest, error) {
	rows, err := q.db.Query(ctx, listRetconRequests, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RetconRequest{}
	for rows.Next() {
		var i RetconRequest
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.TargetChapterID,
			&i.Status,
			&i.ImpactScope,
			&i.ProposedChange,
			&i.Reason,
			&i.RequestedBy,
			&i.ApprovedBy,
			&i.AppliedBy,
			&i.BaseOfficialCanonVersionID,
			&i.WorkspaceBranchID,
			&i.ListenerImpact,
			&i.CreatedAt,
			&i.ApprovedAt,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRetconRequest = `-- name: UpdateRetconRequest :one
UPDATE retcon_requests
SET status = $2,
    approved_by = $3,
    applied_by = $4,
    approved_at = CASE WHEN $2 = 'APPROVED' THEN NOW() ELSE approved_at END,
    applied_at = CASE WHEN $2 = 'APPLIED' THEN NOW() ELSE applied_at END
WHERE id = $1
RETURNING id, story_id, target_chapter_id, status, impact_scope, proposed_change, reason,
          requested_by, approved_by, applied_by, base_official_canon_version_id,
          workspace_branch_id, listener_impact, created_at, approved_at, applied_at
`

type UpdateRetconRequestParams struct {
	ID         pgtype.UUID `json:"id"`
	Status     string      `json:"status"`
	ApprovedBy pgtype.UUID `json:"approved_by"`
	AppliedBy  pgtype.UUID `json:"applied_by"`
}

func (q *Queries) UpdateRetconRequest(ctx context.Context, arg UpdateRetconRequestParams) (RetconRequest, error) {
	row := q.db.QueryRow(ctx, updateRetconRequest,
		arg.ID,
		arg.Status,
		arg.ApprovedBy,
		arg.AppliedBy,
	)
	var i RetconRequest
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.TargetChapterID,
		&i.Status,
		&i.ImpactScope,
		&i.ProposedChange,
		&i.Reason,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.AppliedBy,
		&i.BaseOfficialCanonVersionID,
		&i.WorkspaceBranchID,
		&i.ListenerImpact,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.AppliedAt,
	)
	return i, err
}
