// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: story.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContentProfileVersion = `-- name: CreateContentProfileVersion :one
INSERT INTO story_content_profile_versions (id, story_id, version_no, profile, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, story_id, version_no, profile, base_policy_version_id, created_by, created_at
`

type CreateContentProfileVersionParams struct {
	ID        pgtype.UUID `json:"id"`
	StoryID   pgtype.UUID `json:"story_id"`
	VersionNo int32       `json:"version_no"`
	Profile   []byte      `json:"profile"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateContentProfileVersion(ctx context.Context, arg CreateContentProfileVersionParams) (StoryContentProfileVersion, error) {
	row := q.db.QueryRow(ctx, createContentProfileVersion,
		arg.ID,
		arg.StoryID,
		arg.VersionNo,
		arg.Profile,
		arg.CreatedBy,
	)
	var i StoryContentProfileVersion
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.VersionNo,
		&i.Profile,
		&i.BasePolicyVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createGenerationPolicy = `-- name: CreateGenerationPolicy :exec
INSERT INTO story_generation_policies (story_id, minimum_audio_duration_sec, target_audio_duration_sec,
                                       content_origin, language, narration_language, policy_version, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateGenerationPolicyParams struct {
	StoryID                 pgtype.UUID `json:"story_id"`
	MinimumAudioDurationSec int32       `json:"minimum_audio_duration_sec"`
	TargetAudioDurationSec  int32       `json:"target_audio_duration_sec"`
	ContentOrigin           string      `json:"content_origin"`
	Language                string      `json:"language"`
	NarrationLanguage       string      `json:"narration_language"`
	PolicyVersion           int32       `json:"policy_version"`
	CreatedBy               pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateGenerationPolicy(ctx context.Context, arg CreateGenerationPolicyParams) error {
	_, err := q.db.Exec(ctx, createGenerationPolicy,
		arg.StoryID,
		arg.MinimumAudioDurationSec,
		arg.TargetAudioDurationSec,
		arg.ContentOrigin,
		arg.Language,
		arg.NarrationLanguage,
		arg.PolicyVersion,
		arg.CreatedBy,
	)
	return err
}

const createStory = `-- name: CreateStory :one
INSERT INTO stories (id, slug, title, description, status, visibility, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, slug, title, description, status, visibility, planning_mode, planning_phase,
          public_rating, public_warnings, cover_asset_id, current_story_bible_version_id,
          current_ending_plan_version_id, current_content_profile_version_id,
          current_official_canon_version_id, public_since, last_published_at,
          status_before_archive, created_by, created_at, updated_at, archived_at
`

type CreateStoryParams struct {
	ID          pgtype.UUID `json:"id"`
	Slug        string      `json:"slug"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	Visibility  string      `json:"visibility"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateStory(ctx context.Context, arg CreateStoryParams) (Story, error) {
	row := q.db.QueryRow(ctx, createStory,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Visibility,
		arg.CreatedBy,
	)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.PlanningMode,
		&i.PlanningPhase,
		&i.PublicRating,
		&i.PublicWarnings,
		&i.CoverAssetID,
		&i.CurrentStoryBibleVersionID,
		&i.CurrentEndingPlanVersionID,
		&i.CurrentContentProfileVersionID,
		&i.CurrentOfficialCanonVersionID,
		&i.PublicSince,
		&i.LastPublishedAt,
		&i.StatusBeforeArchive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createStoryAsset = `-- name: CreateStoryAsset :one
INSERT INTO story_assets (id, story_id, type, storage_key, mime_type, size_bytes, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, story_id, type, storage_key, mime_type, size_bytes, checksum, rights_status, status, created_by, created_at
`

type CreateStoryAssetParams struct {
	ID         pgtype.UUID `json:"id"`
	StoryID    pgtype.UUID `json:"story_id"`
	Type       string      `json:"type"`
	StorageKey string      `json:"storage_key"`
	MimeType   pgtype.Text `json:"mime_type"`
	SizeBytes  pgtype.Int8 `json:"size_bytes"`
	Status     string      `json:"status"`
	CreatedBy  pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateStoryAsset(ctx context.Context, arg CreateStoryAssetParams) (StoryAsset, error) {
	row := q.db.QueryRow(ctx, createStoryAsset,
		arg.ID,
		arg.StoryID,
		arg.Type,
		arg.StorageKey,
		arg.MimeType,
		arg.SizeBytes,
		arg.Status,
		arg.CreatedBy,
	)
	var i StoryAsset
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.Type,
		&i.StorageKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.Checksum,
		&i.RightsStatus,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentContentProfile = `-- name: GetCurrentContentProfile :one
SELECT id, story_id, version_no, profile, base_policy_version_id, created_by, created_at
FROM story_content_profile_versions
WHERE story_id = $1
ORDER BY version_no DESC
LIMIT 1
`

func (q *Queries) GetCurrentContentProfile(ctx context.Context, storyID pgtype.UUID) (StoryContentProfileVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentContentProfile, storyID)
	var i StoryContentProfileVersion
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.VersionNo,
		&i.Profile,
		&i.BasePolicyVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getStory = `-- name: GetStory :one
SELECT id, slug, title, description, status, visibility, planning_mode, planning_phase,
       public_rating, public_warnings, cover_asset_id, current_story_bible_version_id,
       current_ending_plan_version_id, current_content_profile_version_id,
       current_official_canon_version_id, public_since, last_published_at,
       status_before_archive, created_by, created_at, updated_at, archived_at
FROM stories
WHERE id = $1
`

func (q *Queries) GetStory(ctx context.Context, id pgtype.UUID) (Story, error) {
	row := q.db.QueryRow(ctx, getStory, id)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.PlanningMode,
		&i.PlanningPhase,
		&i.PublicRating,
		&i.PublicWarnings,
		&i.CoverAssetID,
		&i.CurrentStoryBibleVersionID,
		&i.CurrentEndingPlanVersionID,
		&i.CurrentContentProfileVersionID,
		&i.CurrentOfficialCanonVersionID,
		&i.PublicSince,
		&i.LastPublishedAt,
		&i.StatusBeforeArchive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getWorkflowSettings = `-- name: GetWorkflowSettings :one
SELECT story_id, batch_generation_size, creative_autonomy, preferred_text_provider,
       preferred_text_model, preferred_tts_provider, preferred_voice_id, pause_before_tts,
       auto_ai_review, planning_horizon, fallback_policy, updated_by, updated_at
FROM story_workflow_settings
WHERE story_id = $1
`

func (q *Queries) GetWorkflowSettings(ctx context.Context, storyID pgtype.UUID) (StoryWorkflowSetting, error) {
	row := q.db.QueryRow(ctx, getWorkflowSettings, storyID)
	var i StoryWorkflowSetting
	err := row.Scan(
		&i.StoryID,
		&i.BatchGenerationSize,
		&i.CreativeAutonomy,
		&i.PreferredTextProvider,
		&i.PreferredTextModel,
		&i.PreferredTtsProvider,
		&i.PreferredVoiceID,
		&i.PauseBeforeTts,
		&i.AutoAiReview,
		&i.PlanningHorizon,
		&i.FallbackPolicy,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const hasGenerationPolicy = `-- name: HasGenerationPolicy :one
SELECT EXISTS(SELECT 1 FROM story_generation_policies WHERE story_id = $1)
`

func (q *Queries) HasGenerationPolicy(ctx context.Context, storyID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasGenerationPolicy, storyID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const linkCoverAsset = `-- name: LinkCoverAsset :exec
UPDATE stories SET cover_asset_id = $2, updated_at = NOW() WHERE id = $1
`

type LinkCoverAssetParams struct {
	ID           pgtype.UUID `json:"id"`
	CoverAssetID pgtype.UUID `json:"cover_asset_id"`
}

func (q *Queries) LinkCoverAsset(ctx context.Context, arg LinkCoverAssetParams) error {
	_, err := q.db.Exec(ctx, linkCoverAsset, arg.ID, arg.CoverAssetID)
	return err
}

const listGenres = `-- name: ListGenres :many
SELECT id, slug, name FROM genres ORDER BY name
`

func (q *Queries) ListGenres(ctx context.Context) ([]Genre, error) {
	rows, err := q.db.Query(ctx, listGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Genre{}
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStories = `-- name: ListStories :many
SELECT id, slug, title, description, status, visibility, planning_mode, planning_phase,
       public_rating, public_warnings, cover_asset_id, current_story_bible_version_id,
       current_ending_plan_version_id, current_content_profile_version_id,
       current_official_canon_version_id, public_since, last_published_at,
       status_before_archive, created_by, created_at, updated_at, archived_at
FROM stories
WHERE ($1::boolean = FALSE OR visibility = 'PUBLIC')
ORDER BY created_at DESC
`

func (q *Queries) ListStories(ctx context.Context, dollar_1 bool) ([]Story, error) {
	rows, err := q.db.Query(ctx, listStories, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Story{}
	for rows.Next() {
		var i Story
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.PlanningMode,
			&i.PlanningPhase,
			&i.PublicRating,
			&i.PublicWarnings,
			&i.CoverAssetID,
			&i.CurrentStoryBibleVersionID,
			&i.CurrentEndingPlanVersionID,
			&i.CurrentContentProfileVersionID,
			&i.CurrentOfficialCanonVersionID,
			&i.PublicSince,
			&i.LastPublishedAt,
			&i.StatusBeforeArchive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextContentProfileVersion = `-- name: NextContentProfileVersion :one
SELECT COALESCE(MAX(version_no), 0) + 1
FROM story_content_profile_versions
WHERE story_id = $1
`

func (q *Queries) NextContentProfileVersion(ctx context.Context, storyID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextContentProfileVersion, storyID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const searchStories = `-- name: SearchStories :many
SELECT id, slug, title, description, status, visibility, planning_mode, planning_phase,
       public_rating, public_warnings, cover_asset_id, current_story_bible_version_id,
       current_ending_plan_version_id, current_content_profile_version_id,
       current_official_canon_version_id, public_since, last_published_at,
       status_before_archive, created_by, created_at, updated_at, archived_at
FROM stories
WHERE visibility = 'PUBLIC'
  AND ($1::text = '' OR title ILIKE '%' || $1 || '%' OR description ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR id IN (
        SELECT sg.story_id FROM story_genres sg
        JOIN genres g ON g.id = sg.genre_id
        WHERE g.slug = $2
      ))
ORDER BY
  CASE WHEN $3::text = 'TITLE' THEN title END ASC,
  CASE WHEN $3::text = 'NEW' THEN public_since END DESC NULLS LAST,
  CASE WHEN $3::text = 'RECENTLY_UPDATED' THEN last_published_at END DESC NULLS LAST,
  created_at DESC
`

type SearchStoriesParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) SearchStories(ctx context.Context, arg SearchStoriesParams) ([]Story, error) {
	rows, err := q.db.Query(ctx, searchStories, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Story{}
	for rows.Next() {
		var i Story
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.PlanningMode,
			&i.PlanningPhase,
			&i.PublicRating,
			&i.PublicWarnings,
			&i.CoverAssetID,
			&i.CurrentStoryBibleVersionID,
			&i.CurrentEndingPlanVersionID,
			&i.CurrentContentProfileVersionID,
			&i.CurrentOfficialCanonVersionID,
			&i.PublicSince,
			&i.LastPublishedAt,
			&i.StatusBeforeArchive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slugExists = `-- name: SlugExists :one
SELECT EXISTS(SELECT 1 FROM stories WHERE slug = $1)
`

func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateStory = `-- name: UpdateStory :one
UPDATE stories
SET title = $2, description = $3, status = $4, visibility = $5,
    status_before_archive = $6, cover_asset_id = $7, updated_at = NOW()
WHERE id = $1
RETURNING id, slug, title, description, status, visibility, planning_mode, planning_phase,
          public_rating, public_warnings, cover_asset_id, current_story_bible_version_id,
          current_ending_plan_version_id, current_content_profile_version_id,
          current_official_canon_version_id, public_since, last_published_at,
          status_before_archive, created_by, created_at, updated_at, archived_at
`

type UpdateStoryParams struct {
	ID                  pgtype.UUID `json:"id"`
	Title               string      `json:"title"`
	Description         pgtype.Text `json:"description"`
	Status              string      `json:"status"`
	Visibility          string      `json:"visibility"`
	StatusBeforeArchive pgtype.Text `json:"status_before_archive"`
	CoverAssetID        pgtype.UUID `json:"cover_asset_id"`
}

func (q *Queries) UpdateStory(ctx context.Context, arg UpdateStoryParams) (Story, error) {
	row := q.db.QueryRow(ctx, updateStory,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Visibility,
		arg.StatusBeforeArchive,
		arg.CoverAssetID,
	)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.PlanningMode,
		&i.PlanningPhase,
		&i.PublicRating,
		&i.PublicWarnings,
		&i.CoverAssetID,
		&i.CurrentStoryBibleVersionID,
		&i.CurrentEndingPlanVersionID,
		&i.CurrentContentProfileVersionID,
		&i.CurrentOfficialCanonVersionID,
		&i.PublicSince,
		&i.LastPublishedAt,
		&i.StatusBeforeArchive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const upsertWorkflowSettings = `-- name: UpsertWorkflowSettings :one
INSERT INTO story_workflow_settings (story_id, batch_generation_size, creative_autonomy,
                                     preferred_text_provider, preferred_text_model,
                                     preferred_tts_provider, preferred_voice_id, pause_before_tts,
                                     auto_ai_review, planning_horizon, fallback_policy, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (story_id) DO UPDATE
SET batch_generation_size = EXCLUDED.batch_generation_size,
    creative_autonomy = EXCLUDED.creative_autonomy,
    preferred_text_provider = EXCLUDED.preferred_text_provider,
    preferred_text_model = EXCLUDED.preferred_text_model,
    preferred_tts_provider = EXCLUDED.preferred_tts_provider,
    preferred_voice_id = EXCLUDED.preferred_voice_id,
    pause_before_tts = EXCLUDED.pause_before_tts,
    auto_ai_review = EXCLUDED.auto_ai_review,
    planning_horizon = EXCLUDED.planning_horizon,
    fallback_policy = EXCLUDED.fallback_policy,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW()
RETURNING story_id, batch_generation_size, creative_autonomy, preferred_text_provider,
          preferred_text_model, preferred_tts_provider, preferred_voice_id, pause_before_tts,
          auto_ai_review, planning_horizon, fallback_policy, updated_by, updated_at
`

type UpsertWorkflowSettingsParams struct {
	StoryID               pgtype.UUID `json:"story_id"`
	BatchGenerationSize   pgtype.Int4 `json:"batch_generation_size"`
	CreativeAutonomy      pgtype.Text `json:"creative_autonomy"`
	PreferredTextProvider pgtype.Text `json:"preferred_text_provider"`
	PreferredTextModel    pgtype.Text `json:"preferred_text_model"`
	PreferredTtsProvider  pgtype.Text `json:"preferred_tts_provider"`
	PreferredVoiceID      pgtype.Text `json:"preferred_voice_id"`
	PauseBeforeTts        bool        `json:"pause_before_tts"`
	AutoAiReview          bool        `json:"auto_ai_review"`
	PlanningHorizon       pgtype.Int4 `json:"planning_horizon"`
	FallbackPolicy        []byte      `json:"fallback_policy"`
	UpdatedBy             pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpsertWorkflowSettings(ctx context.Context, arg UpsertWorkflowSettingsParams) (StoryWorkflowSetting, error) {
	row := q.db.QueryRow(ctx, upsertWorkflowSettings,
		arg.StoryID,
		arg.BatchGenerationSize,
		arg.CreativeAutonomy,
		arg.PreferredTextProvider,
		arg.PreferredTextModel,
		arg.PreferredTtsProvider,
		arg.PreferredVoiceID,
		arg.PauseBeforeTts,
		arg.AutoAiReview,
		arg.PlanningHorizon,
		arg.FallbackPolicy,
		arg.UpdatedBy,
	)
	var i StoryWorkflowSetting
	err := row.Scan(
		&i.StoryID,
		&i.BatchGenerationSize,
		&i.CreativeAutonomy,
		&i.PreferredTextProvider,
		&i.PreferredTextModel,
		&i.PreferredTtsProvider,
		&i.PreferredVoiceID,
		&i.PauseBeforeTts,
		&i.AutoAiReview,
		&i.PlanningHorizon,
		&i.FallbackPolicy,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
