// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: writer_jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWriterGenerationJob = `-- name: CreateWriterGenerationJob :one

WITH frozen_input AS (
    SELECT c.id AS chapter_id, c.current_plan_revision_id AS plan_revision_id
    FROM chapters c
    JOIN chapter_plan_revisions p
      ON p.id = c.current_plan_revision_id
     AND p.chapter_id = c.id
    WHERE c.id = $9
      AND c.current_plan_revision_id IS NOT NULL
), created_job AS (
    INSERT INTO generation_jobs (
        id, run_id, job_type, status, priority, input_fingerprint,
        attempt_count, max_attempts
    )
    SELECT $1, $2, $3, $4, $5, $6, $7, $8
    FROM frozen_input
    RETURNING id, run_id, job_type, status, priority, available_at, input_fingerprint,
              attempt_count, max_attempts, locked_by, lock_expires_at, started_at,
              completed_at, last_error_class, last_error_code, output_ref, created_at
), bound_input AS (
    INSERT INTO generation_job_writer_inputs (job_id, chapter_id, plan_revision_id)
    SELECT j.id, f.chapter_id, f.plan_revision_id
    FROM created_job j
    CROSS JOIN frozen_input f
    RETURNING job_id
)
SELECT j.id, j.run_id, j.job_type, j.status, j.priority, j.available_at,
       j.input_fingerprint, j.attempt_count, j.max_attempts, j.locked_by,
       j.lock_expires_at, j.started_at, j.completed_at, j.last_error_class,
       j.last_error_code, j.output_ref, j.created_at
FROM created_job j
JOIN bound_input b ON b.job_id = j.id
`

type CreateWriterGenerationJobParams struct {
	ID               pgtype.UUID `json:"id"`
	RunID            pgtype.UUID `json:"run_id"`
	JobType          string      `json:"job_type"`
	Status           string      `json:"status"`
	Priority         int32       `json:"priority"`
	InputFingerprint pgtype.Text `json:"input_fingerprint"`
	AttemptCount     int32       `json:"attempt_count"`
	MaxAttempts      int32       `json:"max_attempts"`
	ID_2             pgtype.UUID `json:"id_2"`
}

type CreateWriterGenerationJobRow struct {
	ID               pgtype.UUID        `json:"id"`
	RunID            pgtype.UUID        `json:"run_id"`
	JobType          string             `json:"job_type"`
	Status           string             `json:"status"`
	Priority         int32              `json:"priority"`
	AvailableAt      pgtype.Timestamptz `json:"available_at"`
	InputFingerprint pgtype.Text        `json:"input_fingerprint"`
	AttemptCount     int32              `json:"attempt_count"`
	MaxAttempts      int32              `json:"max_attempts"`
	LockedBy         pgtype.Text        `json:"locked_by"`
	LockExpiresAt    pgtype.Timestamptz `json:"lock_expires_at"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	LastErrorClass   pgtype.Text        `json:"last_error_class"`
	LastErrorCode    pgtype.Text        `json:"last_error_code"`
	OutputRef        []byte             `json:"output_ref"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

// ============================================================
// WRITER job immutable input + durable output
// ============================================================
func (q *Queries) CreateWriterGenerationJob(ctx context.Context, arg CreateWriterGenerationJobParams) (CreateWriterGenerationJobRow, error) {
	row := q.db.QueryRow(ctx, createWriterGenerationJob,
		arg.ID,
		arg.RunID,
		arg.JobType,
		arg.Status,
		arg.Priority,
		arg.InputFingerprint,
		arg.AttemptCount,
		arg.MaxAttempts,
		arg.ID_2,
	)
	var i CreateWriterGenerationJobRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobType,
		&i.Status,
		&i.Priority,
		&i.AvailableAt,
		&i.InputFingerprint,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastErrorClass,
		&i.LastErrorCode,
		&i.OutputRef,
		&i.CreatedAt,
	)
	return i, err
}

const getWriterJobInput = `-- name: GetWriterJobInput :one
SELECT wi.job_id, wi.chapter_id, wi.plan_revision_id, p.plan, p.base_canon_version_id
FROM generation_job_writer_inputs wi
JOIN chapter_plan_revisions p
  ON p.id = wi.plan_revision_id
 AND p.chapter_id = wi.chapter_id
WHERE wi.job_id = $1
`

type GetWriterJobInputRow struct {
	JobID              pgtype.UUID `json:"job_id"`
	ChapterID          pgtype.UUID `json:"chapter_id"`
	PlanRevisionID     pgtype.UUID `json:"plan_revision_id"`
	Plan               []byte      `json:"plan"`
	BaseCanonVersionID pgtype.UUID `json:"base_canon_version_id"`
}

func (q *Queries) GetWriterJobInput(ctx context.Context, jobID pgtype.UUID) (GetWriterJobInputRow, error) {
	row := q.db.QueryRow(ctx, getWriterJobInput, jobID)
	var i GetWriterJobInputRow
	err := row.Scan(
		&i.JobID,
		&i.ChapterID,
		&i.PlanRevisionID,
		&i.Plan,
		&i.BaseCanonVersionID,
	)
	return i, err
}

const getWriterOutput = `-- name: GetWriterOutput :one
SELECT id, chapter_id, revision_no, content_text, source_type, based_on_revision_id,
       plan_revision_id, base_canon_version_id, generation_run_id, retcon_request_id,
       status, created_by, created_at
FROM chapter_content_revisions
WHERE generation_run_id = $1
  AND plan_revision_id = $2
  AND source_type = 'AI_GENERATED'
ORDER BY revision_no DESC
LIMIT 1
`

type GetWriterOutputParams struct {
	GenerationRunID pgtype.UUID `json:"generation_run_id"`
	PlanRevisionID  pgtype.UUID `json:"plan_revision_id"`
}

func (q *Queries) GetWriterOutput(ctx context.Context, arg GetWriterOutputParams) (ChapterContentRevision, error) {
	row := q.db.QueryRow(ctx, getWriterOutput, arg.GenerationRunID, arg.PlanRevisionID)
	var i ChapterContentRevision
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.RevisionNo,
		&i.ContentText,
		&i.SourceType,
		&i.BasedOnRevisionID,
		&i.PlanRevisionID,
		&i.BaseCanonVersionID,
		&i.GenerationRunID,
		&i.RetconRequestID,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateWriterJobOutputRef = `-- name: UpdateWriterJobOutputRef :one
UPDATE generation_jobs
SET output_ref = $2
WHERE id = $1
RETURNING id, run_id, job_type, status, priority, available_at, input_fingerprint,
          attempt_count, max_attempts, locked_by, lock_expires_at, started_at,
          completed_at, last_error_class, last_error_code, output_ref, created_at
`

type UpdateWriterJobOutputRefParams struct {
	ID        pgtype.UUID `json:"id"`
	OutputRef []byte      `json:"output_ref"`
}

func (q *Queries) UpdateWriterJobOutputRef(ctx context.Context, arg UpdateWriterJobOutputRefParams) (GenerationJob, error) {
	row := q.db.QueryRow(ctx, updateWriterJobOutputRef, arg.ID, arg.OutputRef)
	var i GenerationJob
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobType,
		&i.Status,
		&i.Priority,
		&i.AvailableAt,
		&i.InputFingerprint,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockExpiresAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastErrorClass,
		&i.LastErrorCode,
		&i.OutputRef,
		&i.CreatedAt,
	)
	return i, err
}
